//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bizapps_test.MVC.AsmxPostServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PostSoap", Namespace="http://postservice.org/")]
    [System.SerializableAttribute()]
    public partial class PostSoap : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BodyField;
        
        private System.DateTime CreationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostImageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Body {
            get {
                return this.BodyField;
            }
            set {
                if ((object.ReferenceEquals(this.BodyField, value) != true)) {
                    this.BodyField = value;
                    this.RaisePropertyChanged("Body");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime CreationDate {
            get {
                return this.CreationDateField;
            }
            set {
                if ((this.CreationDateField.Equals(value) != true)) {
                    this.CreationDateField = value;
                    this.RaisePropertyChanged("CreationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string PostImage {
            get {
                return this.PostImageField;
            }
            set {
                if ((object.ReferenceEquals(this.PostImageField, value) != true)) {
                    this.PostImageField = value;
                    this.RaisePropertyChanged("PostImage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CategorySoap", Namespace="http://postservice.org/")]
    [System.SerializableAttribute()]
    public partial class CategorySoap : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CategoryName {
            get {
                return this.CategoryNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryNameField, value) != true)) {
                    this.CategoryNameField = value;
                    this.RaisePropertyChanged("CategoryName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://postservice.org/", ConfigurationName="AsmxPostServiceReference.AsmxPostServiceSoap")]
    public interface AsmxPostServiceSoap {
        
        // CODEGEN: Generating message contract since element name postSoap from namespace http://postservice.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://postservice.org/CreatePost", ReplyAction="*")]
        bizapps_test.MVC.AsmxPostServiceReference.CreatePostResponse CreatePost(bizapps_test.MVC.AsmxPostServiceReference.CreatePostRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://postservice.org/CreatePost", ReplyAction="*")]
        System.Threading.Tasks.Task<bizapps_test.MVC.AsmxPostServiceReference.CreatePostResponse> CreatePostAsync(bizapps_test.MVC.AsmxPostServiceReference.CreatePostRequest request);
        
        // CODEGEN: Generating message contract since element name postSoap from namespace http://postservice.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://postservice.org/UpdatePost", ReplyAction="*")]
        bizapps_test.MVC.AsmxPostServiceReference.UpdatePostResponse UpdatePost(bizapps_test.MVC.AsmxPostServiceReference.UpdatePostRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://postservice.org/UpdatePost", ReplyAction="*")]
        System.Threading.Tasks.Task<bizapps_test.MVC.AsmxPostServiceReference.UpdatePostResponse> UpdatePostAsync(bizapps_test.MVC.AsmxPostServiceReference.UpdatePostRequest request);
        
        // CODEGEN: Generating message contract since element name postSoap from namespace http://postservice.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://postservice.org/DeletePost", ReplyAction="*")]
        bizapps_test.MVC.AsmxPostServiceReference.DeletePostResponse DeletePost(bizapps_test.MVC.AsmxPostServiceReference.DeletePostRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://postservice.org/DeletePost", ReplyAction="*")]
        System.Threading.Tasks.Task<bizapps_test.MVC.AsmxPostServiceReference.DeletePostResponse> DeletePostAsync(bizapps_test.MVC.AsmxPostServiceReference.DeletePostRequest request);
        
        // CODEGEN: Generating message contract since element name GetUserPostsResult from namespace http://postservice.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://postservice.org/GetUserPosts", ReplyAction="*")]
        bizapps_test.MVC.AsmxPostServiceReference.GetUserPostsResponse GetUserPosts(bizapps_test.MVC.AsmxPostServiceReference.GetUserPostsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://postservice.org/GetUserPosts", ReplyAction="*")]
        System.Threading.Tasks.Task<bizapps_test.MVC.AsmxPostServiceReference.GetUserPostsResponse> GetUserPostsAsync(bizapps_test.MVC.AsmxPostServiceReference.GetUserPostsRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace http://postservice.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://postservice.org/GetUserPostsByUserName", ReplyAction="*")]
        bizapps_test.MVC.AsmxPostServiceReference.GetUserPostsByUserNameResponse GetUserPostsByUserName(bizapps_test.MVC.AsmxPostServiceReference.GetUserPostsByUserNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://postservice.org/GetUserPostsByUserName", ReplyAction="*")]
        System.Threading.Tasks.Task<bizapps_test.MVC.AsmxPostServiceReference.GetUserPostsByUserNameResponse> GetUserPostsByUserNameAsync(bizapps_test.MVC.AsmxPostServiceReference.GetUserPostsByUserNameRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace http://postservice.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://postservice.org/GetPostsByUserNameWithoutCategory", ReplyAction="*")]
        bizapps_test.MVC.AsmxPostServiceReference.GetPostsByUserNameWithoutCategoryResponse GetPostsByUserNameWithoutCategory(bizapps_test.MVC.AsmxPostServiceReference.GetPostsByUserNameWithoutCategoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://postservice.org/GetPostsByUserNameWithoutCategory", ReplyAction="*")]
        System.Threading.Tasks.Task<bizapps_test.MVC.AsmxPostServiceReference.GetPostsByUserNameWithoutCategoryResponse> GetPostsByUserNameWithoutCategoryAsync(bizapps_test.MVC.AsmxPostServiceReference.GetPostsByUserNameWithoutCategoryRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace http://postservice.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://postservice.org/GetPostsByUserNameAndCategory", ReplyAction="*")]
        bizapps_test.MVC.AsmxPostServiceReference.GetPostsByUserNameAndCategoryResponse GetPostsByUserNameAndCategory(bizapps_test.MVC.AsmxPostServiceReference.GetPostsByUserNameAndCategoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://postservice.org/GetPostsByUserNameAndCategory", ReplyAction="*")]
        System.Threading.Tasks.Task<bizapps_test.MVC.AsmxPostServiceReference.GetPostsByUserNameAndCategoryResponse> GetPostsByUserNameAndCategoryAsync(bizapps_test.MVC.AsmxPostServiceReference.GetPostsByUserNameAndCategoryRequest request);
        
        // CODEGEN: Generating message contract since element name GetPostResult from namespace http://postservice.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://postservice.org/GetPost", ReplyAction="*")]
        bizapps_test.MVC.AsmxPostServiceReference.GetPostResponse GetPost(bizapps_test.MVC.AsmxPostServiceReference.GetPostRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://postservice.org/GetPost", ReplyAction="*")]
        System.Threading.Tasks.Task<bizapps_test.MVC.AsmxPostServiceReference.GetPostResponse> GetPostAsync(bizapps_test.MVC.AsmxPostServiceReference.GetPostRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreatePostRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreatePost", Namespace="http://postservice.org/", Order=0)]
        public bizapps_test.MVC.AsmxPostServiceReference.CreatePostRequestBody Body;
        
        public CreatePostRequest() {
        }
        
        public CreatePostRequest(bizapps_test.MVC.AsmxPostServiceReference.CreatePostRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://postservice.org/")]
    public partial class CreatePostRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public bizapps_test.MVC.AsmxPostServiceReference.PostSoap postSoap;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public bizapps_test.MVC.AsmxPostServiceReference.CategorySoap[] categorySoapList;
        
        public CreatePostRequestBody() {
        }
        
        public CreatePostRequestBody(bizapps_test.MVC.AsmxPostServiceReference.PostSoap postSoap, int userId, bizapps_test.MVC.AsmxPostServiceReference.CategorySoap[] categorySoapList) {
            this.postSoap = postSoap;
            this.userId = userId;
            this.categorySoapList = categorySoapList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreatePostResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreatePostResponse", Namespace="http://postservice.org/", Order=0)]
        public bizapps_test.MVC.AsmxPostServiceReference.CreatePostResponseBody Body;
        
        public CreatePostResponse() {
        }
        
        public CreatePostResponse(bizapps_test.MVC.AsmxPostServiceReference.CreatePostResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://postservice.org/")]
    public partial class CreatePostResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int CreatePostResult;
        
        public CreatePostResponseBody() {
        }
        
        public CreatePostResponseBody(int CreatePostResult) {
            this.CreatePostResult = CreatePostResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdatePostRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdatePost", Namespace="http://postservice.org/", Order=0)]
        public bizapps_test.MVC.AsmxPostServiceReference.UpdatePostRequestBody Body;
        
        public UpdatePostRequest() {
        }
        
        public UpdatePostRequest(bizapps_test.MVC.AsmxPostServiceReference.UpdatePostRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://postservice.org/")]
    public partial class UpdatePostRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public bizapps_test.MVC.AsmxPostServiceReference.PostSoap postSoap;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public bizapps_test.MVC.AsmxPostServiceReference.CategorySoap[] categorySoapList;
        
        public UpdatePostRequestBody() {
        }
        
        public UpdatePostRequestBody(bizapps_test.MVC.AsmxPostServiceReference.PostSoap postSoap, bizapps_test.MVC.AsmxPostServiceReference.CategorySoap[] categorySoapList) {
            this.postSoap = postSoap;
            this.categorySoapList = categorySoapList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdatePostResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdatePostResponse", Namespace="http://postservice.org/", Order=0)]
        public bizapps_test.MVC.AsmxPostServiceReference.UpdatePostResponseBody Body;
        
        public UpdatePostResponse() {
        }
        
        public UpdatePostResponse(bizapps_test.MVC.AsmxPostServiceReference.UpdatePostResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://postservice.org/")]
    public partial class UpdatePostResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UpdatePostResult;
        
        public UpdatePostResponseBody() {
        }
        
        public UpdatePostResponseBody(int UpdatePostResult) {
            this.UpdatePostResult = UpdatePostResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeletePostRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeletePost", Namespace="http://postservice.org/", Order=0)]
        public bizapps_test.MVC.AsmxPostServiceReference.DeletePostRequestBody Body;
        
        public DeletePostRequest() {
        }
        
        public DeletePostRequest(bizapps_test.MVC.AsmxPostServiceReference.DeletePostRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://postservice.org/")]
    public partial class DeletePostRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public bizapps_test.MVC.AsmxPostServiceReference.PostSoap postSoap;
        
        public DeletePostRequestBody() {
        }
        
        public DeletePostRequestBody(bizapps_test.MVC.AsmxPostServiceReference.PostSoap postSoap) {
            this.postSoap = postSoap;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeletePostResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeletePostResponse", Namespace="http://postservice.org/", Order=0)]
        public bizapps_test.MVC.AsmxPostServiceReference.DeletePostResponseBody Body;
        
        public DeletePostResponse() {
        }
        
        public DeletePostResponse(bizapps_test.MVC.AsmxPostServiceReference.DeletePostResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://postservice.org/")]
    public partial class DeletePostResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int DeletePostResult;
        
        public DeletePostResponseBody() {
        }
        
        public DeletePostResponseBody(int DeletePostResult) {
            this.DeletePostResult = DeletePostResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserPostsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserPosts", Namespace="http://postservice.org/", Order=0)]
        public bizapps_test.MVC.AsmxPostServiceReference.GetUserPostsRequestBody Body;
        
        public GetUserPostsRequest() {
        }
        
        public GetUserPostsRequest(bizapps_test.MVC.AsmxPostServiceReference.GetUserPostsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://postservice.org/")]
    public partial class GetUserPostsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int userId;
        
        public GetUserPostsRequestBody() {
        }
        
        public GetUserPostsRequestBody(int userId) {
            this.userId = userId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserPostsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserPostsResponse", Namespace="http://postservice.org/", Order=0)]
        public bizapps_test.MVC.AsmxPostServiceReference.GetUserPostsResponseBody Body;
        
        public GetUserPostsResponse() {
        }
        
        public GetUserPostsResponse(bizapps_test.MVC.AsmxPostServiceReference.GetUserPostsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://postservice.org/")]
    public partial class GetUserPostsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public bizapps_test.MVC.AsmxPostServiceReference.PostSoap[] GetUserPostsResult;
        
        public GetUserPostsResponseBody() {
        }
        
        public GetUserPostsResponseBody(bizapps_test.MVC.AsmxPostServiceReference.PostSoap[] GetUserPostsResult) {
            this.GetUserPostsResult = GetUserPostsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserPostsByUserNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserPostsByUserName", Namespace="http://postservice.org/", Order=0)]
        public bizapps_test.MVC.AsmxPostServiceReference.GetUserPostsByUserNameRequestBody Body;
        
        public GetUserPostsByUserNameRequest() {
        }
        
        public GetUserPostsByUserNameRequest(bizapps_test.MVC.AsmxPostServiceReference.GetUserPostsByUserNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://postservice.org/")]
    public partial class GetUserPostsByUserNameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        public GetUserPostsByUserNameRequestBody() {
        }
        
        public GetUserPostsByUserNameRequestBody(string userName) {
            this.userName = userName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserPostsByUserNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserPostsByUserNameResponse", Namespace="http://postservice.org/", Order=0)]
        public bizapps_test.MVC.AsmxPostServiceReference.GetUserPostsByUserNameResponseBody Body;
        
        public GetUserPostsByUserNameResponse() {
        }
        
        public GetUserPostsByUserNameResponse(bizapps_test.MVC.AsmxPostServiceReference.GetUserPostsByUserNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://postservice.org/")]
    public partial class GetUserPostsByUserNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public bizapps_test.MVC.AsmxPostServiceReference.PostSoap[] GetUserPostsByUserNameResult;
        
        public GetUserPostsByUserNameResponseBody() {
        }
        
        public GetUserPostsByUserNameResponseBody(bizapps_test.MVC.AsmxPostServiceReference.PostSoap[] GetUserPostsByUserNameResult) {
            this.GetUserPostsByUserNameResult = GetUserPostsByUserNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPostsByUserNameWithoutCategoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPostsByUserNameWithoutCategory", Namespace="http://postservice.org/", Order=0)]
        public bizapps_test.MVC.AsmxPostServiceReference.GetPostsByUserNameWithoutCategoryRequestBody Body;
        
        public GetPostsByUserNameWithoutCategoryRequest() {
        }
        
        public GetPostsByUserNameWithoutCategoryRequest(bizapps_test.MVC.AsmxPostServiceReference.GetPostsByUserNameWithoutCategoryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://postservice.org/")]
    public partial class GetPostsByUserNameWithoutCategoryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        public GetPostsByUserNameWithoutCategoryRequestBody() {
        }
        
        public GetPostsByUserNameWithoutCategoryRequestBody(string userName) {
            this.userName = userName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPostsByUserNameWithoutCategoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPostsByUserNameWithoutCategoryResponse", Namespace="http://postservice.org/", Order=0)]
        public bizapps_test.MVC.AsmxPostServiceReference.GetPostsByUserNameWithoutCategoryResponseBody Body;
        
        public GetPostsByUserNameWithoutCategoryResponse() {
        }
        
        public GetPostsByUserNameWithoutCategoryResponse(bizapps_test.MVC.AsmxPostServiceReference.GetPostsByUserNameWithoutCategoryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://postservice.org/")]
    public partial class GetPostsByUserNameWithoutCategoryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public bizapps_test.MVC.AsmxPostServiceReference.PostSoap[] GetPostsByUserNameWithoutCategoryResult;
        
        public GetPostsByUserNameWithoutCategoryResponseBody() {
        }
        
        public GetPostsByUserNameWithoutCategoryResponseBody(bizapps_test.MVC.AsmxPostServiceReference.PostSoap[] GetPostsByUserNameWithoutCategoryResult) {
            this.GetPostsByUserNameWithoutCategoryResult = GetPostsByUserNameWithoutCategoryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPostsByUserNameAndCategoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPostsByUserNameAndCategory", Namespace="http://postservice.org/", Order=0)]
        public bizapps_test.MVC.AsmxPostServiceReference.GetPostsByUserNameAndCategoryRequestBody Body;
        
        public GetPostsByUserNameAndCategoryRequest() {
        }
        
        public GetPostsByUserNameAndCategoryRequest(bizapps_test.MVC.AsmxPostServiceReference.GetPostsByUserNameAndCategoryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://postservice.org/")]
    public partial class GetPostsByUserNameAndCategoryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int categoryId;
        
        public GetPostsByUserNameAndCategoryRequestBody() {
        }
        
        public GetPostsByUserNameAndCategoryRequestBody(string userName, int categoryId) {
            this.userName = userName;
            this.categoryId = categoryId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPostsByUserNameAndCategoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPostsByUserNameAndCategoryResponse", Namespace="http://postservice.org/", Order=0)]
        public bizapps_test.MVC.AsmxPostServiceReference.GetPostsByUserNameAndCategoryResponseBody Body;
        
        public GetPostsByUserNameAndCategoryResponse() {
        }
        
        public GetPostsByUserNameAndCategoryResponse(bizapps_test.MVC.AsmxPostServiceReference.GetPostsByUserNameAndCategoryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://postservice.org/")]
    public partial class GetPostsByUserNameAndCategoryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public bizapps_test.MVC.AsmxPostServiceReference.PostSoap[] GetPostsByUserNameAndCategoryResult;
        
        public GetPostsByUserNameAndCategoryResponseBody() {
        }
        
        public GetPostsByUserNameAndCategoryResponseBody(bizapps_test.MVC.AsmxPostServiceReference.PostSoap[] GetPostsByUserNameAndCategoryResult) {
            this.GetPostsByUserNameAndCategoryResult = GetPostsByUserNameAndCategoryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPostRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPost", Namespace="http://postservice.org/", Order=0)]
        public bizapps_test.MVC.AsmxPostServiceReference.GetPostRequestBody Body;
        
        public GetPostRequest() {
        }
        
        public GetPostRequest(bizapps_test.MVC.AsmxPostServiceReference.GetPostRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://postservice.org/")]
    public partial class GetPostRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int postId;
        
        public GetPostRequestBody() {
        }
        
        public GetPostRequestBody(int postId) {
            this.postId = postId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPostResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPostResponse", Namespace="http://postservice.org/", Order=0)]
        public bizapps_test.MVC.AsmxPostServiceReference.GetPostResponseBody Body;
        
        public GetPostResponse() {
        }
        
        public GetPostResponse(bizapps_test.MVC.AsmxPostServiceReference.GetPostResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://postservice.org/")]
    public partial class GetPostResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public bizapps_test.MVC.AsmxPostServiceReference.PostSoap GetPostResult;
        
        public GetPostResponseBody() {
        }
        
        public GetPostResponseBody(bizapps_test.MVC.AsmxPostServiceReference.PostSoap GetPostResult) {
            this.GetPostResult = GetPostResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AsmxPostServiceSoapChannel : bizapps_test.MVC.AsmxPostServiceReference.AsmxPostServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AsmxPostServiceSoapClient : System.ServiceModel.ClientBase<bizapps_test.MVC.AsmxPostServiceReference.AsmxPostServiceSoap>, bizapps_test.MVC.AsmxPostServiceReference.AsmxPostServiceSoap {
        
        public AsmxPostServiceSoapClient() {
        }
        
        public AsmxPostServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AsmxPostServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AsmxPostServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AsmxPostServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bizapps_test.MVC.AsmxPostServiceReference.CreatePostResponse bizapps_test.MVC.AsmxPostServiceReference.AsmxPostServiceSoap.CreatePost(bizapps_test.MVC.AsmxPostServiceReference.CreatePostRequest request) {
            return base.Channel.CreatePost(request);
        }
        
        public int CreatePost(bizapps_test.MVC.AsmxPostServiceReference.PostSoap postSoap, int userId, bizapps_test.MVC.AsmxPostServiceReference.CategorySoap[] categorySoapList) {
            bizapps_test.MVC.AsmxPostServiceReference.CreatePostRequest inValue = new bizapps_test.MVC.AsmxPostServiceReference.CreatePostRequest();
            inValue.Body = new bizapps_test.MVC.AsmxPostServiceReference.CreatePostRequestBody();
            inValue.Body.postSoap = postSoap;
            inValue.Body.userId = userId;
            inValue.Body.categorySoapList = categorySoapList;
            bizapps_test.MVC.AsmxPostServiceReference.CreatePostResponse retVal = ((bizapps_test.MVC.AsmxPostServiceReference.AsmxPostServiceSoap)(this)).CreatePost(inValue);
            return retVal.Body.CreatePostResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<bizapps_test.MVC.AsmxPostServiceReference.CreatePostResponse> bizapps_test.MVC.AsmxPostServiceReference.AsmxPostServiceSoap.CreatePostAsync(bizapps_test.MVC.AsmxPostServiceReference.CreatePostRequest request) {
            return base.Channel.CreatePostAsync(request);
        }
        
        public System.Threading.Tasks.Task<bizapps_test.MVC.AsmxPostServiceReference.CreatePostResponse> CreatePostAsync(bizapps_test.MVC.AsmxPostServiceReference.PostSoap postSoap, int userId, bizapps_test.MVC.AsmxPostServiceReference.CategorySoap[] categorySoapList) {
            bizapps_test.MVC.AsmxPostServiceReference.CreatePostRequest inValue = new bizapps_test.MVC.AsmxPostServiceReference.CreatePostRequest();
            inValue.Body = new bizapps_test.MVC.AsmxPostServiceReference.CreatePostRequestBody();
            inValue.Body.postSoap = postSoap;
            inValue.Body.userId = userId;
            inValue.Body.categorySoapList = categorySoapList;
            return ((bizapps_test.MVC.AsmxPostServiceReference.AsmxPostServiceSoap)(this)).CreatePostAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bizapps_test.MVC.AsmxPostServiceReference.UpdatePostResponse bizapps_test.MVC.AsmxPostServiceReference.AsmxPostServiceSoap.UpdatePost(bizapps_test.MVC.AsmxPostServiceReference.UpdatePostRequest request) {
            return base.Channel.UpdatePost(request);
        }
        
        public int UpdatePost(bizapps_test.MVC.AsmxPostServiceReference.PostSoap postSoap, bizapps_test.MVC.AsmxPostServiceReference.CategorySoap[] categorySoapList) {
            bizapps_test.MVC.AsmxPostServiceReference.UpdatePostRequest inValue = new bizapps_test.MVC.AsmxPostServiceReference.UpdatePostRequest();
            inValue.Body = new bizapps_test.MVC.AsmxPostServiceReference.UpdatePostRequestBody();
            inValue.Body.postSoap = postSoap;
            inValue.Body.categorySoapList = categorySoapList;
            bizapps_test.MVC.AsmxPostServiceReference.UpdatePostResponse retVal = ((bizapps_test.MVC.AsmxPostServiceReference.AsmxPostServiceSoap)(this)).UpdatePost(inValue);
            return retVal.Body.UpdatePostResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<bizapps_test.MVC.AsmxPostServiceReference.UpdatePostResponse> bizapps_test.MVC.AsmxPostServiceReference.AsmxPostServiceSoap.UpdatePostAsync(bizapps_test.MVC.AsmxPostServiceReference.UpdatePostRequest request) {
            return base.Channel.UpdatePostAsync(request);
        }
        
        public System.Threading.Tasks.Task<bizapps_test.MVC.AsmxPostServiceReference.UpdatePostResponse> UpdatePostAsync(bizapps_test.MVC.AsmxPostServiceReference.PostSoap postSoap, bizapps_test.MVC.AsmxPostServiceReference.CategorySoap[] categorySoapList) {
            bizapps_test.MVC.AsmxPostServiceReference.UpdatePostRequest inValue = new bizapps_test.MVC.AsmxPostServiceReference.UpdatePostRequest();
            inValue.Body = new bizapps_test.MVC.AsmxPostServiceReference.UpdatePostRequestBody();
            inValue.Body.postSoap = postSoap;
            inValue.Body.categorySoapList = categorySoapList;
            return ((bizapps_test.MVC.AsmxPostServiceReference.AsmxPostServiceSoap)(this)).UpdatePostAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bizapps_test.MVC.AsmxPostServiceReference.DeletePostResponse bizapps_test.MVC.AsmxPostServiceReference.AsmxPostServiceSoap.DeletePost(bizapps_test.MVC.AsmxPostServiceReference.DeletePostRequest request) {
            return base.Channel.DeletePost(request);
        }
        
        public int DeletePost(bizapps_test.MVC.AsmxPostServiceReference.PostSoap postSoap) {
            bizapps_test.MVC.AsmxPostServiceReference.DeletePostRequest inValue = new bizapps_test.MVC.AsmxPostServiceReference.DeletePostRequest();
            inValue.Body = new bizapps_test.MVC.AsmxPostServiceReference.DeletePostRequestBody();
            inValue.Body.postSoap = postSoap;
            bizapps_test.MVC.AsmxPostServiceReference.DeletePostResponse retVal = ((bizapps_test.MVC.AsmxPostServiceReference.AsmxPostServiceSoap)(this)).DeletePost(inValue);
            return retVal.Body.DeletePostResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<bizapps_test.MVC.AsmxPostServiceReference.DeletePostResponse> bizapps_test.MVC.AsmxPostServiceReference.AsmxPostServiceSoap.DeletePostAsync(bizapps_test.MVC.AsmxPostServiceReference.DeletePostRequest request) {
            return base.Channel.DeletePostAsync(request);
        }
        
        public System.Threading.Tasks.Task<bizapps_test.MVC.AsmxPostServiceReference.DeletePostResponse> DeletePostAsync(bizapps_test.MVC.AsmxPostServiceReference.PostSoap postSoap) {
            bizapps_test.MVC.AsmxPostServiceReference.DeletePostRequest inValue = new bizapps_test.MVC.AsmxPostServiceReference.DeletePostRequest();
            inValue.Body = new bizapps_test.MVC.AsmxPostServiceReference.DeletePostRequestBody();
            inValue.Body.postSoap = postSoap;
            return ((bizapps_test.MVC.AsmxPostServiceReference.AsmxPostServiceSoap)(this)).DeletePostAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bizapps_test.MVC.AsmxPostServiceReference.GetUserPostsResponse bizapps_test.MVC.AsmxPostServiceReference.AsmxPostServiceSoap.GetUserPosts(bizapps_test.MVC.AsmxPostServiceReference.GetUserPostsRequest request) {
            return base.Channel.GetUserPosts(request);
        }
        
        public bizapps_test.MVC.AsmxPostServiceReference.PostSoap[] GetUserPosts(int userId) {
            bizapps_test.MVC.AsmxPostServiceReference.GetUserPostsRequest inValue = new bizapps_test.MVC.AsmxPostServiceReference.GetUserPostsRequest();
            inValue.Body = new bizapps_test.MVC.AsmxPostServiceReference.GetUserPostsRequestBody();
            inValue.Body.userId = userId;
            bizapps_test.MVC.AsmxPostServiceReference.GetUserPostsResponse retVal = ((bizapps_test.MVC.AsmxPostServiceReference.AsmxPostServiceSoap)(this)).GetUserPosts(inValue);
            return retVal.Body.GetUserPostsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<bizapps_test.MVC.AsmxPostServiceReference.GetUserPostsResponse> bizapps_test.MVC.AsmxPostServiceReference.AsmxPostServiceSoap.GetUserPostsAsync(bizapps_test.MVC.AsmxPostServiceReference.GetUserPostsRequest request) {
            return base.Channel.GetUserPostsAsync(request);
        }
        
        public System.Threading.Tasks.Task<bizapps_test.MVC.AsmxPostServiceReference.GetUserPostsResponse> GetUserPostsAsync(int userId) {
            bizapps_test.MVC.AsmxPostServiceReference.GetUserPostsRequest inValue = new bizapps_test.MVC.AsmxPostServiceReference.GetUserPostsRequest();
            inValue.Body = new bizapps_test.MVC.AsmxPostServiceReference.GetUserPostsRequestBody();
            inValue.Body.userId = userId;
            return ((bizapps_test.MVC.AsmxPostServiceReference.AsmxPostServiceSoap)(this)).GetUserPostsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bizapps_test.MVC.AsmxPostServiceReference.GetUserPostsByUserNameResponse bizapps_test.MVC.AsmxPostServiceReference.AsmxPostServiceSoap.GetUserPostsByUserName(bizapps_test.MVC.AsmxPostServiceReference.GetUserPostsByUserNameRequest request) {
            return base.Channel.GetUserPostsByUserName(request);
        }
        
        public bizapps_test.MVC.AsmxPostServiceReference.PostSoap[] GetUserPostsByUserName(string userName) {
            bizapps_test.MVC.AsmxPostServiceReference.GetUserPostsByUserNameRequest inValue = new bizapps_test.MVC.AsmxPostServiceReference.GetUserPostsByUserNameRequest();
            inValue.Body = new bizapps_test.MVC.AsmxPostServiceReference.GetUserPostsByUserNameRequestBody();
            inValue.Body.userName = userName;
            bizapps_test.MVC.AsmxPostServiceReference.GetUserPostsByUserNameResponse retVal = ((bizapps_test.MVC.AsmxPostServiceReference.AsmxPostServiceSoap)(this)).GetUserPostsByUserName(inValue);
            return retVal.Body.GetUserPostsByUserNameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<bizapps_test.MVC.AsmxPostServiceReference.GetUserPostsByUserNameResponse> bizapps_test.MVC.AsmxPostServiceReference.AsmxPostServiceSoap.GetUserPostsByUserNameAsync(bizapps_test.MVC.AsmxPostServiceReference.GetUserPostsByUserNameRequest request) {
            return base.Channel.GetUserPostsByUserNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<bizapps_test.MVC.AsmxPostServiceReference.GetUserPostsByUserNameResponse> GetUserPostsByUserNameAsync(string userName) {
            bizapps_test.MVC.AsmxPostServiceReference.GetUserPostsByUserNameRequest inValue = new bizapps_test.MVC.AsmxPostServiceReference.GetUserPostsByUserNameRequest();
            inValue.Body = new bizapps_test.MVC.AsmxPostServiceReference.GetUserPostsByUserNameRequestBody();
            inValue.Body.userName = userName;
            return ((bizapps_test.MVC.AsmxPostServiceReference.AsmxPostServiceSoap)(this)).GetUserPostsByUserNameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bizapps_test.MVC.AsmxPostServiceReference.GetPostsByUserNameWithoutCategoryResponse bizapps_test.MVC.AsmxPostServiceReference.AsmxPostServiceSoap.GetPostsByUserNameWithoutCategory(bizapps_test.MVC.AsmxPostServiceReference.GetPostsByUserNameWithoutCategoryRequest request) {
            return base.Channel.GetPostsByUserNameWithoutCategory(request);
        }
        
        public bizapps_test.MVC.AsmxPostServiceReference.PostSoap[] GetPostsByUserNameWithoutCategory(string userName) {
            bizapps_test.MVC.AsmxPostServiceReference.GetPostsByUserNameWithoutCategoryRequest inValue = new bizapps_test.MVC.AsmxPostServiceReference.GetPostsByUserNameWithoutCategoryRequest();
            inValue.Body = new bizapps_test.MVC.AsmxPostServiceReference.GetPostsByUserNameWithoutCategoryRequestBody();
            inValue.Body.userName = userName;
            bizapps_test.MVC.AsmxPostServiceReference.GetPostsByUserNameWithoutCategoryResponse retVal = ((bizapps_test.MVC.AsmxPostServiceReference.AsmxPostServiceSoap)(this)).GetPostsByUserNameWithoutCategory(inValue);
            return retVal.Body.GetPostsByUserNameWithoutCategoryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<bizapps_test.MVC.AsmxPostServiceReference.GetPostsByUserNameWithoutCategoryResponse> bizapps_test.MVC.AsmxPostServiceReference.AsmxPostServiceSoap.GetPostsByUserNameWithoutCategoryAsync(bizapps_test.MVC.AsmxPostServiceReference.GetPostsByUserNameWithoutCategoryRequest request) {
            return base.Channel.GetPostsByUserNameWithoutCategoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<bizapps_test.MVC.AsmxPostServiceReference.GetPostsByUserNameWithoutCategoryResponse> GetPostsByUserNameWithoutCategoryAsync(string userName) {
            bizapps_test.MVC.AsmxPostServiceReference.GetPostsByUserNameWithoutCategoryRequest inValue = new bizapps_test.MVC.AsmxPostServiceReference.GetPostsByUserNameWithoutCategoryRequest();
            inValue.Body = new bizapps_test.MVC.AsmxPostServiceReference.GetPostsByUserNameWithoutCategoryRequestBody();
            inValue.Body.userName = userName;
            return ((bizapps_test.MVC.AsmxPostServiceReference.AsmxPostServiceSoap)(this)).GetPostsByUserNameWithoutCategoryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bizapps_test.MVC.AsmxPostServiceReference.GetPostsByUserNameAndCategoryResponse bizapps_test.MVC.AsmxPostServiceReference.AsmxPostServiceSoap.GetPostsByUserNameAndCategory(bizapps_test.MVC.AsmxPostServiceReference.GetPostsByUserNameAndCategoryRequest request) {
            return base.Channel.GetPostsByUserNameAndCategory(request);
        }
        
        public bizapps_test.MVC.AsmxPostServiceReference.PostSoap[] GetPostsByUserNameAndCategory(string userName, int categoryId) {
            bizapps_test.MVC.AsmxPostServiceReference.GetPostsByUserNameAndCategoryRequest inValue = new bizapps_test.MVC.AsmxPostServiceReference.GetPostsByUserNameAndCategoryRequest();
            inValue.Body = new bizapps_test.MVC.AsmxPostServiceReference.GetPostsByUserNameAndCategoryRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.categoryId = categoryId;
            bizapps_test.MVC.AsmxPostServiceReference.GetPostsByUserNameAndCategoryResponse retVal = ((bizapps_test.MVC.AsmxPostServiceReference.AsmxPostServiceSoap)(this)).GetPostsByUserNameAndCategory(inValue);
            return retVal.Body.GetPostsByUserNameAndCategoryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<bizapps_test.MVC.AsmxPostServiceReference.GetPostsByUserNameAndCategoryResponse> bizapps_test.MVC.AsmxPostServiceReference.AsmxPostServiceSoap.GetPostsByUserNameAndCategoryAsync(bizapps_test.MVC.AsmxPostServiceReference.GetPostsByUserNameAndCategoryRequest request) {
            return base.Channel.GetPostsByUserNameAndCategoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<bizapps_test.MVC.AsmxPostServiceReference.GetPostsByUserNameAndCategoryResponse> GetPostsByUserNameAndCategoryAsync(string userName, int categoryId) {
            bizapps_test.MVC.AsmxPostServiceReference.GetPostsByUserNameAndCategoryRequest inValue = new bizapps_test.MVC.AsmxPostServiceReference.GetPostsByUserNameAndCategoryRequest();
            inValue.Body = new bizapps_test.MVC.AsmxPostServiceReference.GetPostsByUserNameAndCategoryRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.categoryId = categoryId;
            return ((bizapps_test.MVC.AsmxPostServiceReference.AsmxPostServiceSoap)(this)).GetPostsByUserNameAndCategoryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bizapps_test.MVC.AsmxPostServiceReference.GetPostResponse bizapps_test.MVC.AsmxPostServiceReference.AsmxPostServiceSoap.GetPost(bizapps_test.MVC.AsmxPostServiceReference.GetPostRequest request) {
            return base.Channel.GetPost(request);
        }
        
        public bizapps_test.MVC.AsmxPostServiceReference.PostSoap GetPost(int postId) {
            bizapps_test.MVC.AsmxPostServiceReference.GetPostRequest inValue = new bizapps_test.MVC.AsmxPostServiceReference.GetPostRequest();
            inValue.Body = new bizapps_test.MVC.AsmxPostServiceReference.GetPostRequestBody();
            inValue.Body.postId = postId;
            bizapps_test.MVC.AsmxPostServiceReference.GetPostResponse retVal = ((bizapps_test.MVC.AsmxPostServiceReference.AsmxPostServiceSoap)(this)).GetPost(inValue);
            return retVal.Body.GetPostResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<bizapps_test.MVC.AsmxPostServiceReference.GetPostResponse> bizapps_test.MVC.AsmxPostServiceReference.AsmxPostServiceSoap.GetPostAsync(bizapps_test.MVC.AsmxPostServiceReference.GetPostRequest request) {
            return base.Channel.GetPostAsync(request);
        }
        
        public System.Threading.Tasks.Task<bizapps_test.MVC.AsmxPostServiceReference.GetPostResponse> GetPostAsync(int postId) {
            bizapps_test.MVC.AsmxPostServiceReference.GetPostRequest inValue = new bizapps_test.MVC.AsmxPostServiceReference.GetPostRequest();
            inValue.Body = new bizapps_test.MVC.AsmxPostServiceReference.GetPostRequestBody();
            inValue.Body.postId = postId;
            return ((bizapps_test.MVC.AsmxPostServiceReference.AsmxPostServiceSoap)(this)).GetPostAsync(inValue);
        }
    }
}
