//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bizapps_test.MVC.WcfCategoryServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CategoryDC", Namespace="http://schemas.datacontract.org/2004/07/bizapps_test.SL.Wcf_Services.DataContract" +
        "s")]
    [System.SerializableAttribute()]
    public partial class CategoryDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CategoryName {
            get {
                return this.CategoryNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryNameField, value) != true)) {
                    this.CategoryNameField = value;
                    this.RaisePropertyChanged("CategoryName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WcfCategoryServiceReference.IWcfCategoryService")]
    public interface IWcfCategoryService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfCategoryService/CreateCategory", ReplyAction="http://tempuri.org/IWcfCategoryService/CreateCategoryResponse")]
        int CreateCategory(bizapps_test.MVC.WcfCategoryServiceReference.CategoryDC categoryDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfCategoryService/CreateCategory", ReplyAction="http://tempuri.org/IWcfCategoryService/CreateCategoryResponse")]
        System.Threading.Tasks.Task<int> CreateCategoryAsync(bizapps_test.MVC.WcfCategoryServiceReference.CategoryDC categoryDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfCategoryService/UpdateCategory", ReplyAction="http://tempuri.org/IWcfCategoryService/UpdateCategoryResponse")]
        int UpdateCategory(bizapps_test.MVC.WcfCategoryServiceReference.CategoryDC categoryDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfCategoryService/UpdateCategory", ReplyAction="http://tempuri.org/IWcfCategoryService/UpdateCategoryResponse")]
        System.Threading.Tasks.Task<int> UpdateCategoryAsync(bizapps_test.MVC.WcfCategoryServiceReference.CategoryDC categoryDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfCategoryService/DeleteCategory", ReplyAction="http://tempuri.org/IWcfCategoryService/DeleteCategoryResponse")]
        int DeleteCategory(bizapps_test.MVC.WcfCategoryServiceReference.CategoryDC categoryDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfCategoryService/DeleteCategory", ReplyAction="http://tempuri.org/IWcfCategoryService/DeleteCategoryResponse")]
        System.Threading.Tasks.Task<int> DeleteCategoryAsync(bizapps_test.MVC.WcfCategoryServiceReference.CategoryDC categoryDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfCategoryService/GetAllCategories", ReplyAction="http://tempuri.org/IWcfCategoryService/GetAllCategoriesResponse")]
        bizapps_test.MVC.WcfCategoryServiceReference.CategoryDC[] GetAllCategories();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfCategoryService/GetAllCategories", ReplyAction="http://tempuri.org/IWcfCategoryService/GetAllCategoriesResponse")]
        System.Threading.Tasks.Task<bizapps_test.MVC.WcfCategoryServiceReference.CategoryDC[]> GetAllCategoriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfCategoryService/GetPostCategories", ReplyAction="http://tempuri.org/IWcfCategoryService/GetPostCategoriesResponse")]
        bizapps_test.MVC.WcfCategoryServiceReference.CategoryDC[] GetPostCategories(int postId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfCategoryService/GetPostCategories", ReplyAction="http://tempuri.org/IWcfCategoryService/GetPostCategoriesResponse")]
        System.Threading.Tasks.Task<bizapps_test.MVC.WcfCategoryServiceReference.CategoryDC[]> GetPostCategoriesAsync(int postId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfCategoryService/GetBlogCategories", ReplyAction="http://tempuri.org/IWcfCategoryService/GetBlogCategoriesResponse")]
        bizapps_test.MVC.WcfCategoryServiceReference.CategoryDC[] GetBlogCategories(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfCategoryService/GetBlogCategories", ReplyAction="http://tempuri.org/IWcfCategoryService/GetBlogCategoriesResponse")]
        System.Threading.Tasks.Task<bizapps_test.MVC.WcfCategoryServiceReference.CategoryDC[]> GetBlogCategoriesAsync(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfCategoryService/GetCategoryById", ReplyAction="http://tempuri.org/IWcfCategoryService/GetCategoryByIdResponse")]
        bizapps_test.MVC.WcfCategoryServiceReference.CategoryDC GetCategoryById(int categoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfCategoryService/GetCategoryById", ReplyAction="http://tempuri.org/IWcfCategoryService/GetCategoryByIdResponse")]
        System.Threading.Tasks.Task<bizapps_test.MVC.WcfCategoryServiceReference.CategoryDC> GetCategoryByIdAsync(int categoryId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWcfCategoryServiceChannel : bizapps_test.MVC.WcfCategoryServiceReference.IWcfCategoryService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WcfCategoryServiceClient : System.ServiceModel.ClientBase<bizapps_test.MVC.WcfCategoryServiceReference.IWcfCategoryService>, bizapps_test.MVC.WcfCategoryServiceReference.IWcfCategoryService {
        
        public WcfCategoryServiceClient() {
        }
        
        public WcfCategoryServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WcfCategoryServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WcfCategoryServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WcfCategoryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int CreateCategory(bizapps_test.MVC.WcfCategoryServiceReference.CategoryDC categoryDC) {
            return base.Channel.CreateCategory(categoryDC);
        }
        
        public System.Threading.Tasks.Task<int> CreateCategoryAsync(bizapps_test.MVC.WcfCategoryServiceReference.CategoryDC categoryDC) {
            return base.Channel.CreateCategoryAsync(categoryDC);
        }
        
        public int UpdateCategory(bizapps_test.MVC.WcfCategoryServiceReference.CategoryDC categoryDC) {
            return base.Channel.UpdateCategory(categoryDC);
        }
        
        public System.Threading.Tasks.Task<int> UpdateCategoryAsync(bizapps_test.MVC.WcfCategoryServiceReference.CategoryDC categoryDC) {
            return base.Channel.UpdateCategoryAsync(categoryDC);
        }
        
        public int DeleteCategory(bizapps_test.MVC.WcfCategoryServiceReference.CategoryDC categoryDC) {
            return base.Channel.DeleteCategory(categoryDC);
        }
        
        public System.Threading.Tasks.Task<int> DeleteCategoryAsync(bizapps_test.MVC.WcfCategoryServiceReference.CategoryDC categoryDC) {
            return base.Channel.DeleteCategoryAsync(categoryDC);
        }
        
        public bizapps_test.MVC.WcfCategoryServiceReference.CategoryDC[] GetAllCategories() {
            return base.Channel.GetAllCategories();
        }
        
        public System.Threading.Tasks.Task<bizapps_test.MVC.WcfCategoryServiceReference.CategoryDC[]> GetAllCategoriesAsync() {
            return base.Channel.GetAllCategoriesAsync();
        }
        
        public bizapps_test.MVC.WcfCategoryServiceReference.CategoryDC[] GetPostCategories(int postId) {
            return base.Channel.GetPostCategories(postId);
        }
        
        public System.Threading.Tasks.Task<bizapps_test.MVC.WcfCategoryServiceReference.CategoryDC[]> GetPostCategoriesAsync(int postId) {
            return base.Channel.GetPostCategoriesAsync(postId);
        }
        
        public bizapps_test.MVC.WcfCategoryServiceReference.CategoryDC[] GetBlogCategories(string userName) {
            return base.Channel.GetBlogCategories(userName);
        }
        
        public System.Threading.Tasks.Task<bizapps_test.MVC.WcfCategoryServiceReference.CategoryDC[]> GetBlogCategoriesAsync(string userName) {
            return base.Channel.GetBlogCategoriesAsync(userName);
        }
        
        public bizapps_test.MVC.WcfCategoryServiceReference.CategoryDC GetCategoryById(int categoryId) {
            return base.Channel.GetCategoryById(categoryId);
        }
        
        public System.Threading.Tasks.Task<bizapps_test.MVC.WcfCategoryServiceReference.CategoryDC> GetCategoryByIdAsync(int categoryId) {
            return base.Channel.GetCategoryByIdAsync(categoryId);
        }
    }
}
