//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bizapps_test.MVC.AsmxCategoryServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CategorySoap", Namespace="http://category.org/")]
    [System.SerializableAttribute()]
    public partial class CategorySoap : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CategoryName {
            get {
                return this.CategoryNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryNameField, value) != true)) {
                    this.CategoryNameField = value;
                    this.RaisePropertyChanged("CategoryName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://category.org/", ConfigurationName="AsmxCategoryServiceReference.AsmxCategoryServiceSoap")]
    public interface AsmxCategoryServiceSoap {
        
        // CODEGEN: Generating message contract since element name categorySoap from namespace http://category.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://category.org/CreateCategory", ReplyAction="*")]
        bizapps_test.MVC.AsmxCategoryServiceReference.CreateCategoryResponse CreateCategory(bizapps_test.MVC.AsmxCategoryServiceReference.CreateCategoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://category.org/CreateCategory", ReplyAction="*")]
        System.Threading.Tasks.Task<bizapps_test.MVC.AsmxCategoryServiceReference.CreateCategoryResponse> CreateCategoryAsync(bizapps_test.MVC.AsmxCategoryServiceReference.CreateCategoryRequest request);
        
        // CODEGEN: Generating message contract since element name categorySoap from namespace http://category.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://category.org/UpdateCategory", ReplyAction="*")]
        bizapps_test.MVC.AsmxCategoryServiceReference.UpdateCategoryResponse UpdateCategory(bizapps_test.MVC.AsmxCategoryServiceReference.UpdateCategoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://category.org/UpdateCategory", ReplyAction="*")]
        System.Threading.Tasks.Task<bizapps_test.MVC.AsmxCategoryServiceReference.UpdateCategoryResponse> UpdateCategoryAsync(bizapps_test.MVC.AsmxCategoryServiceReference.UpdateCategoryRequest request);
        
        // CODEGEN: Generating message contract since element name categorySoap from namespace http://category.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://category.org/DeleteCategory", ReplyAction="*")]
        bizapps_test.MVC.AsmxCategoryServiceReference.DeleteCategoryResponse DeleteCategory(bizapps_test.MVC.AsmxCategoryServiceReference.DeleteCategoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://category.org/DeleteCategory", ReplyAction="*")]
        System.Threading.Tasks.Task<bizapps_test.MVC.AsmxCategoryServiceReference.DeleteCategoryResponse> DeleteCategoryAsync(bizapps_test.MVC.AsmxCategoryServiceReference.DeleteCategoryRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllCategoriesResult from namespace http://category.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://category.org/GetAllCategories", ReplyAction="*")]
        bizapps_test.MVC.AsmxCategoryServiceReference.GetAllCategoriesResponse GetAllCategories(bizapps_test.MVC.AsmxCategoryServiceReference.GetAllCategoriesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://category.org/GetAllCategories", ReplyAction="*")]
        System.Threading.Tasks.Task<bizapps_test.MVC.AsmxCategoryServiceReference.GetAllCategoriesResponse> GetAllCategoriesAsync(bizapps_test.MVC.AsmxCategoryServiceReference.GetAllCategoriesRequest request);
        
        // CODEGEN: Generating message contract since element name GetPostCategoriesResult from namespace http://category.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://category.org/GetPostCategories", ReplyAction="*")]
        bizapps_test.MVC.AsmxCategoryServiceReference.GetPostCategoriesResponse GetPostCategories(bizapps_test.MVC.AsmxCategoryServiceReference.GetPostCategoriesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://category.org/GetPostCategories", ReplyAction="*")]
        System.Threading.Tasks.Task<bizapps_test.MVC.AsmxCategoryServiceReference.GetPostCategoriesResponse> GetPostCategoriesAsync(bizapps_test.MVC.AsmxCategoryServiceReference.GetPostCategoriesRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace http://category.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://category.org/GetBlogCategories", ReplyAction="*")]
        bizapps_test.MVC.AsmxCategoryServiceReference.GetBlogCategoriesResponse GetBlogCategories(bizapps_test.MVC.AsmxCategoryServiceReference.GetBlogCategoriesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://category.org/GetBlogCategories", ReplyAction="*")]
        System.Threading.Tasks.Task<bizapps_test.MVC.AsmxCategoryServiceReference.GetBlogCategoriesResponse> GetBlogCategoriesAsync(bizapps_test.MVC.AsmxCategoryServiceReference.GetBlogCategoriesRequest request);
        
        // CODEGEN: Generating message contract since element name GetCategoryByIdResult from namespace http://category.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://category.org/GetCategoryById", ReplyAction="*")]
        bizapps_test.MVC.AsmxCategoryServiceReference.GetCategoryByIdResponse GetCategoryById(bizapps_test.MVC.AsmxCategoryServiceReference.GetCategoryByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://category.org/GetCategoryById", ReplyAction="*")]
        System.Threading.Tasks.Task<bizapps_test.MVC.AsmxCategoryServiceReference.GetCategoryByIdResponse> GetCategoryByIdAsync(bizapps_test.MVC.AsmxCategoryServiceReference.GetCategoryByIdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateCategoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateCategory", Namespace="http://category.org/", Order=0)]
        public bizapps_test.MVC.AsmxCategoryServiceReference.CreateCategoryRequestBody Body;
        
        public CreateCategoryRequest() {
        }
        
        public CreateCategoryRequest(bizapps_test.MVC.AsmxCategoryServiceReference.CreateCategoryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://category.org/")]
    public partial class CreateCategoryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public bizapps_test.MVC.AsmxCategoryServiceReference.CategorySoap categorySoap;
        
        public CreateCategoryRequestBody() {
        }
        
        public CreateCategoryRequestBody(bizapps_test.MVC.AsmxCategoryServiceReference.CategorySoap categorySoap) {
            this.categorySoap = categorySoap;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateCategoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateCategoryResponse", Namespace="http://category.org/", Order=0)]
        public bizapps_test.MVC.AsmxCategoryServiceReference.CreateCategoryResponseBody Body;
        
        public CreateCategoryResponse() {
        }
        
        public CreateCategoryResponse(bizapps_test.MVC.AsmxCategoryServiceReference.CreateCategoryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://category.org/")]
    public partial class CreateCategoryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int CreateCategoryResult;
        
        public CreateCategoryResponseBody() {
        }
        
        public CreateCategoryResponseBody(int CreateCategoryResult) {
            this.CreateCategoryResult = CreateCategoryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateCategoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateCategory", Namespace="http://category.org/", Order=0)]
        public bizapps_test.MVC.AsmxCategoryServiceReference.UpdateCategoryRequestBody Body;
        
        public UpdateCategoryRequest() {
        }
        
        public UpdateCategoryRequest(bizapps_test.MVC.AsmxCategoryServiceReference.UpdateCategoryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://category.org/")]
    public partial class UpdateCategoryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public bizapps_test.MVC.AsmxCategoryServiceReference.CategorySoap categorySoap;
        
        public UpdateCategoryRequestBody() {
        }
        
        public UpdateCategoryRequestBody(bizapps_test.MVC.AsmxCategoryServiceReference.CategorySoap categorySoap) {
            this.categorySoap = categorySoap;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateCategoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateCategoryResponse", Namespace="http://category.org/", Order=0)]
        public bizapps_test.MVC.AsmxCategoryServiceReference.UpdateCategoryResponseBody Body;
        
        public UpdateCategoryResponse() {
        }
        
        public UpdateCategoryResponse(bizapps_test.MVC.AsmxCategoryServiceReference.UpdateCategoryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://category.org/")]
    public partial class UpdateCategoryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UpdateCategoryResult;
        
        public UpdateCategoryResponseBody() {
        }
        
        public UpdateCategoryResponseBody(int UpdateCategoryResult) {
            this.UpdateCategoryResult = UpdateCategoryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteCategoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteCategory", Namespace="http://category.org/", Order=0)]
        public bizapps_test.MVC.AsmxCategoryServiceReference.DeleteCategoryRequestBody Body;
        
        public DeleteCategoryRequest() {
        }
        
        public DeleteCategoryRequest(bizapps_test.MVC.AsmxCategoryServiceReference.DeleteCategoryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://category.org/")]
    public partial class DeleteCategoryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public bizapps_test.MVC.AsmxCategoryServiceReference.CategorySoap categorySoap;
        
        public DeleteCategoryRequestBody() {
        }
        
        public DeleteCategoryRequestBody(bizapps_test.MVC.AsmxCategoryServiceReference.CategorySoap categorySoap) {
            this.categorySoap = categorySoap;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteCategoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteCategoryResponse", Namespace="http://category.org/", Order=0)]
        public bizapps_test.MVC.AsmxCategoryServiceReference.DeleteCategoryResponseBody Body;
        
        public DeleteCategoryResponse() {
        }
        
        public DeleteCategoryResponse(bizapps_test.MVC.AsmxCategoryServiceReference.DeleteCategoryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://category.org/")]
    public partial class DeleteCategoryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int DeleteCategoryResult;
        
        public DeleteCategoryResponseBody() {
        }
        
        public DeleteCategoryResponseBody(int DeleteCategoryResult) {
            this.DeleteCategoryResult = DeleteCategoryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllCategoriesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllCategories", Namespace="http://category.org/", Order=0)]
        public bizapps_test.MVC.AsmxCategoryServiceReference.GetAllCategoriesRequestBody Body;
        
        public GetAllCategoriesRequest() {
        }
        
        public GetAllCategoriesRequest(bizapps_test.MVC.AsmxCategoryServiceReference.GetAllCategoriesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllCategoriesRequestBody {
        
        public GetAllCategoriesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllCategoriesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllCategoriesResponse", Namespace="http://category.org/", Order=0)]
        public bizapps_test.MVC.AsmxCategoryServiceReference.GetAllCategoriesResponseBody Body;
        
        public GetAllCategoriesResponse() {
        }
        
        public GetAllCategoriesResponse(bizapps_test.MVC.AsmxCategoryServiceReference.GetAllCategoriesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://category.org/")]
    public partial class GetAllCategoriesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public bizapps_test.MVC.AsmxCategoryServiceReference.CategorySoap[] GetAllCategoriesResult;
        
        public GetAllCategoriesResponseBody() {
        }
        
        public GetAllCategoriesResponseBody(bizapps_test.MVC.AsmxCategoryServiceReference.CategorySoap[] GetAllCategoriesResult) {
            this.GetAllCategoriesResult = GetAllCategoriesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPostCategoriesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPostCategories", Namespace="http://category.org/", Order=0)]
        public bizapps_test.MVC.AsmxCategoryServiceReference.GetPostCategoriesRequestBody Body;
        
        public GetPostCategoriesRequest() {
        }
        
        public GetPostCategoriesRequest(bizapps_test.MVC.AsmxCategoryServiceReference.GetPostCategoriesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://category.org/")]
    public partial class GetPostCategoriesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int postId;
        
        public GetPostCategoriesRequestBody() {
        }
        
        public GetPostCategoriesRequestBody(int postId) {
            this.postId = postId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPostCategoriesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPostCategoriesResponse", Namespace="http://category.org/", Order=0)]
        public bizapps_test.MVC.AsmxCategoryServiceReference.GetPostCategoriesResponseBody Body;
        
        public GetPostCategoriesResponse() {
        }
        
        public GetPostCategoriesResponse(bizapps_test.MVC.AsmxCategoryServiceReference.GetPostCategoriesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://category.org/")]
    public partial class GetPostCategoriesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public bizapps_test.MVC.AsmxCategoryServiceReference.CategorySoap[] GetPostCategoriesResult;
        
        public GetPostCategoriesResponseBody() {
        }
        
        public GetPostCategoriesResponseBody(bizapps_test.MVC.AsmxCategoryServiceReference.CategorySoap[] GetPostCategoriesResult) {
            this.GetPostCategoriesResult = GetPostCategoriesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBlogCategoriesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBlogCategories", Namespace="http://category.org/", Order=0)]
        public bizapps_test.MVC.AsmxCategoryServiceReference.GetBlogCategoriesRequestBody Body;
        
        public GetBlogCategoriesRequest() {
        }
        
        public GetBlogCategoriesRequest(bizapps_test.MVC.AsmxCategoryServiceReference.GetBlogCategoriesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://category.org/")]
    public partial class GetBlogCategoriesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        public GetBlogCategoriesRequestBody() {
        }
        
        public GetBlogCategoriesRequestBody(string userName) {
            this.userName = userName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBlogCategoriesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBlogCategoriesResponse", Namespace="http://category.org/", Order=0)]
        public bizapps_test.MVC.AsmxCategoryServiceReference.GetBlogCategoriesResponseBody Body;
        
        public GetBlogCategoriesResponse() {
        }
        
        public GetBlogCategoriesResponse(bizapps_test.MVC.AsmxCategoryServiceReference.GetBlogCategoriesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://category.org/")]
    public partial class GetBlogCategoriesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public bizapps_test.MVC.AsmxCategoryServiceReference.CategorySoap[] GetBlogCategoriesResult;
        
        public GetBlogCategoriesResponseBody() {
        }
        
        public GetBlogCategoriesResponseBody(bizapps_test.MVC.AsmxCategoryServiceReference.CategorySoap[] GetBlogCategoriesResult) {
            this.GetBlogCategoriesResult = GetBlogCategoriesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCategoryByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCategoryById", Namespace="http://category.org/", Order=0)]
        public bizapps_test.MVC.AsmxCategoryServiceReference.GetCategoryByIdRequestBody Body;
        
        public GetCategoryByIdRequest() {
        }
        
        public GetCategoryByIdRequest(bizapps_test.MVC.AsmxCategoryServiceReference.GetCategoryByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://category.org/")]
    public partial class GetCategoryByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int categoryId;
        
        public GetCategoryByIdRequestBody() {
        }
        
        public GetCategoryByIdRequestBody(int categoryId) {
            this.categoryId = categoryId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCategoryByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCategoryByIdResponse", Namespace="http://category.org/", Order=0)]
        public bizapps_test.MVC.AsmxCategoryServiceReference.GetCategoryByIdResponseBody Body;
        
        public GetCategoryByIdResponse() {
        }
        
        public GetCategoryByIdResponse(bizapps_test.MVC.AsmxCategoryServiceReference.GetCategoryByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://category.org/")]
    public partial class GetCategoryByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public bizapps_test.MVC.AsmxCategoryServiceReference.CategorySoap GetCategoryByIdResult;
        
        public GetCategoryByIdResponseBody() {
        }
        
        public GetCategoryByIdResponseBody(bizapps_test.MVC.AsmxCategoryServiceReference.CategorySoap GetCategoryByIdResult) {
            this.GetCategoryByIdResult = GetCategoryByIdResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AsmxCategoryServiceSoapChannel : bizapps_test.MVC.AsmxCategoryServiceReference.AsmxCategoryServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AsmxCategoryServiceSoapClient : System.ServiceModel.ClientBase<bizapps_test.MVC.AsmxCategoryServiceReference.AsmxCategoryServiceSoap>, bizapps_test.MVC.AsmxCategoryServiceReference.AsmxCategoryServiceSoap {
        
        public AsmxCategoryServiceSoapClient() {
        }
        
        public AsmxCategoryServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AsmxCategoryServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AsmxCategoryServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AsmxCategoryServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bizapps_test.MVC.AsmxCategoryServiceReference.CreateCategoryResponse bizapps_test.MVC.AsmxCategoryServiceReference.AsmxCategoryServiceSoap.CreateCategory(bizapps_test.MVC.AsmxCategoryServiceReference.CreateCategoryRequest request) {
            return base.Channel.CreateCategory(request);
        }
        
        public int CreateCategory(bizapps_test.MVC.AsmxCategoryServiceReference.CategorySoap categorySoap) {
            bizapps_test.MVC.AsmxCategoryServiceReference.CreateCategoryRequest inValue = new bizapps_test.MVC.AsmxCategoryServiceReference.CreateCategoryRequest();
            inValue.Body = new bizapps_test.MVC.AsmxCategoryServiceReference.CreateCategoryRequestBody();
            inValue.Body.categorySoap = categorySoap;
            bizapps_test.MVC.AsmxCategoryServiceReference.CreateCategoryResponse retVal = ((bizapps_test.MVC.AsmxCategoryServiceReference.AsmxCategoryServiceSoap)(this)).CreateCategory(inValue);
            return retVal.Body.CreateCategoryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<bizapps_test.MVC.AsmxCategoryServiceReference.CreateCategoryResponse> bizapps_test.MVC.AsmxCategoryServiceReference.AsmxCategoryServiceSoap.CreateCategoryAsync(bizapps_test.MVC.AsmxCategoryServiceReference.CreateCategoryRequest request) {
            return base.Channel.CreateCategoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<bizapps_test.MVC.AsmxCategoryServiceReference.CreateCategoryResponse> CreateCategoryAsync(bizapps_test.MVC.AsmxCategoryServiceReference.CategorySoap categorySoap) {
            bizapps_test.MVC.AsmxCategoryServiceReference.CreateCategoryRequest inValue = new bizapps_test.MVC.AsmxCategoryServiceReference.CreateCategoryRequest();
            inValue.Body = new bizapps_test.MVC.AsmxCategoryServiceReference.CreateCategoryRequestBody();
            inValue.Body.categorySoap = categorySoap;
            return ((bizapps_test.MVC.AsmxCategoryServiceReference.AsmxCategoryServiceSoap)(this)).CreateCategoryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bizapps_test.MVC.AsmxCategoryServiceReference.UpdateCategoryResponse bizapps_test.MVC.AsmxCategoryServiceReference.AsmxCategoryServiceSoap.UpdateCategory(bizapps_test.MVC.AsmxCategoryServiceReference.UpdateCategoryRequest request) {
            return base.Channel.UpdateCategory(request);
        }
        
        public int UpdateCategory(bizapps_test.MVC.AsmxCategoryServiceReference.CategorySoap categorySoap) {
            bizapps_test.MVC.AsmxCategoryServiceReference.UpdateCategoryRequest inValue = new bizapps_test.MVC.AsmxCategoryServiceReference.UpdateCategoryRequest();
            inValue.Body = new bizapps_test.MVC.AsmxCategoryServiceReference.UpdateCategoryRequestBody();
            inValue.Body.categorySoap = categorySoap;
            bizapps_test.MVC.AsmxCategoryServiceReference.UpdateCategoryResponse retVal = ((bizapps_test.MVC.AsmxCategoryServiceReference.AsmxCategoryServiceSoap)(this)).UpdateCategory(inValue);
            return retVal.Body.UpdateCategoryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<bizapps_test.MVC.AsmxCategoryServiceReference.UpdateCategoryResponse> bizapps_test.MVC.AsmxCategoryServiceReference.AsmxCategoryServiceSoap.UpdateCategoryAsync(bizapps_test.MVC.AsmxCategoryServiceReference.UpdateCategoryRequest request) {
            return base.Channel.UpdateCategoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<bizapps_test.MVC.AsmxCategoryServiceReference.UpdateCategoryResponse> UpdateCategoryAsync(bizapps_test.MVC.AsmxCategoryServiceReference.CategorySoap categorySoap) {
            bizapps_test.MVC.AsmxCategoryServiceReference.UpdateCategoryRequest inValue = new bizapps_test.MVC.AsmxCategoryServiceReference.UpdateCategoryRequest();
            inValue.Body = new bizapps_test.MVC.AsmxCategoryServiceReference.UpdateCategoryRequestBody();
            inValue.Body.categorySoap = categorySoap;
            return ((bizapps_test.MVC.AsmxCategoryServiceReference.AsmxCategoryServiceSoap)(this)).UpdateCategoryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bizapps_test.MVC.AsmxCategoryServiceReference.DeleteCategoryResponse bizapps_test.MVC.AsmxCategoryServiceReference.AsmxCategoryServiceSoap.DeleteCategory(bizapps_test.MVC.AsmxCategoryServiceReference.DeleteCategoryRequest request) {
            return base.Channel.DeleteCategory(request);
        }
        
        public int DeleteCategory(bizapps_test.MVC.AsmxCategoryServiceReference.CategorySoap categorySoap) {
            bizapps_test.MVC.AsmxCategoryServiceReference.DeleteCategoryRequest inValue = new bizapps_test.MVC.AsmxCategoryServiceReference.DeleteCategoryRequest();
            inValue.Body = new bizapps_test.MVC.AsmxCategoryServiceReference.DeleteCategoryRequestBody();
            inValue.Body.categorySoap = categorySoap;
            bizapps_test.MVC.AsmxCategoryServiceReference.DeleteCategoryResponse retVal = ((bizapps_test.MVC.AsmxCategoryServiceReference.AsmxCategoryServiceSoap)(this)).DeleteCategory(inValue);
            return retVal.Body.DeleteCategoryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<bizapps_test.MVC.AsmxCategoryServiceReference.DeleteCategoryResponse> bizapps_test.MVC.AsmxCategoryServiceReference.AsmxCategoryServiceSoap.DeleteCategoryAsync(bizapps_test.MVC.AsmxCategoryServiceReference.DeleteCategoryRequest request) {
            return base.Channel.DeleteCategoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<bizapps_test.MVC.AsmxCategoryServiceReference.DeleteCategoryResponse> DeleteCategoryAsync(bizapps_test.MVC.AsmxCategoryServiceReference.CategorySoap categorySoap) {
            bizapps_test.MVC.AsmxCategoryServiceReference.DeleteCategoryRequest inValue = new bizapps_test.MVC.AsmxCategoryServiceReference.DeleteCategoryRequest();
            inValue.Body = new bizapps_test.MVC.AsmxCategoryServiceReference.DeleteCategoryRequestBody();
            inValue.Body.categorySoap = categorySoap;
            return ((bizapps_test.MVC.AsmxCategoryServiceReference.AsmxCategoryServiceSoap)(this)).DeleteCategoryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bizapps_test.MVC.AsmxCategoryServiceReference.GetAllCategoriesResponse bizapps_test.MVC.AsmxCategoryServiceReference.AsmxCategoryServiceSoap.GetAllCategories(bizapps_test.MVC.AsmxCategoryServiceReference.GetAllCategoriesRequest request) {
            return base.Channel.GetAllCategories(request);
        }
        
        public bizapps_test.MVC.AsmxCategoryServiceReference.CategorySoap[] GetAllCategories() {
            bizapps_test.MVC.AsmxCategoryServiceReference.GetAllCategoriesRequest inValue = new bizapps_test.MVC.AsmxCategoryServiceReference.GetAllCategoriesRequest();
            inValue.Body = new bizapps_test.MVC.AsmxCategoryServiceReference.GetAllCategoriesRequestBody();
            bizapps_test.MVC.AsmxCategoryServiceReference.GetAllCategoriesResponse retVal = ((bizapps_test.MVC.AsmxCategoryServiceReference.AsmxCategoryServiceSoap)(this)).GetAllCategories(inValue);
            return retVal.Body.GetAllCategoriesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<bizapps_test.MVC.AsmxCategoryServiceReference.GetAllCategoriesResponse> bizapps_test.MVC.AsmxCategoryServiceReference.AsmxCategoryServiceSoap.GetAllCategoriesAsync(bizapps_test.MVC.AsmxCategoryServiceReference.GetAllCategoriesRequest request) {
            return base.Channel.GetAllCategoriesAsync(request);
        }
        
        public System.Threading.Tasks.Task<bizapps_test.MVC.AsmxCategoryServiceReference.GetAllCategoriesResponse> GetAllCategoriesAsync() {
            bizapps_test.MVC.AsmxCategoryServiceReference.GetAllCategoriesRequest inValue = new bizapps_test.MVC.AsmxCategoryServiceReference.GetAllCategoriesRequest();
            inValue.Body = new bizapps_test.MVC.AsmxCategoryServiceReference.GetAllCategoriesRequestBody();
            return ((bizapps_test.MVC.AsmxCategoryServiceReference.AsmxCategoryServiceSoap)(this)).GetAllCategoriesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bizapps_test.MVC.AsmxCategoryServiceReference.GetPostCategoriesResponse bizapps_test.MVC.AsmxCategoryServiceReference.AsmxCategoryServiceSoap.GetPostCategories(bizapps_test.MVC.AsmxCategoryServiceReference.GetPostCategoriesRequest request) {
            return base.Channel.GetPostCategories(request);
        }
        
        public bizapps_test.MVC.AsmxCategoryServiceReference.CategorySoap[] GetPostCategories(int postId) {
            bizapps_test.MVC.AsmxCategoryServiceReference.GetPostCategoriesRequest inValue = new bizapps_test.MVC.AsmxCategoryServiceReference.GetPostCategoriesRequest();
            inValue.Body = new bizapps_test.MVC.AsmxCategoryServiceReference.GetPostCategoriesRequestBody();
            inValue.Body.postId = postId;
            bizapps_test.MVC.AsmxCategoryServiceReference.GetPostCategoriesResponse retVal = ((bizapps_test.MVC.AsmxCategoryServiceReference.AsmxCategoryServiceSoap)(this)).GetPostCategories(inValue);
            return retVal.Body.GetPostCategoriesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<bizapps_test.MVC.AsmxCategoryServiceReference.GetPostCategoriesResponse> bizapps_test.MVC.AsmxCategoryServiceReference.AsmxCategoryServiceSoap.GetPostCategoriesAsync(bizapps_test.MVC.AsmxCategoryServiceReference.GetPostCategoriesRequest request) {
            return base.Channel.GetPostCategoriesAsync(request);
        }
        
        public System.Threading.Tasks.Task<bizapps_test.MVC.AsmxCategoryServiceReference.GetPostCategoriesResponse> GetPostCategoriesAsync(int postId) {
            bizapps_test.MVC.AsmxCategoryServiceReference.GetPostCategoriesRequest inValue = new bizapps_test.MVC.AsmxCategoryServiceReference.GetPostCategoriesRequest();
            inValue.Body = new bizapps_test.MVC.AsmxCategoryServiceReference.GetPostCategoriesRequestBody();
            inValue.Body.postId = postId;
            return ((bizapps_test.MVC.AsmxCategoryServiceReference.AsmxCategoryServiceSoap)(this)).GetPostCategoriesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bizapps_test.MVC.AsmxCategoryServiceReference.GetBlogCategoriesResponse bizapps_test.MVC.AsmxCategoryServiceReference.AsmxCategoryServiceSoap.GetBlogCategories(bizapps_test.MVC.AsmxCategoryServiceReference.GetBlogCategoriesRequest request) {
            return base.Channel.GetBlogCategories(request);
        }
        
        public bizapps_test.MVC.AsmxCategoryServiceReference.CategorySoap[] GetBlogCategories(string userName) {
            bizapps_test.MVC.AsmxCategoryServiceReference.GetBlogCategoriesRequest inValue = new bizapps_test.MVC.AsmxCategoryServiceReference.GetBlogCategoriesRequest();
            inValue.Body = new bizapps_test.MVC.AsmxCategoryServiceReference.GetBlogCategoriesRequestBody();
            inValue.Body.userName = userName;
            bizapps_test.MVC.AsmxCategoryServiceReference.GetBlogCategoriesResponse retVal = ((bizapps_test.MVC.AsmxCategoryServiceReference.AsmxCategoryServiceSoap)(this)).GetBlogCategories(inValue);
            return retVal.Body.GetBlogCategoriesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<bizapps_test.MVC.AsmxCategoryServiceReference.GetBlogCategoriesResponse> bizapps_test.MVC.AsmxCategoryServiceReference.AsmxCategoryServiceSoap.GetBlogCategoriesAsync(bizapps_test.MVC.AsmxCategoryServiceReference.GetBlogCategoriesRequest request) {
            return base.Channel.GetBlogCategoriesAsync(request);
        }
        
        public System.Threading.Tasks.Task<bizapps_test.MVC.AsmxCategoryServiceReference.GetBlogCategoriesResponse> GetBlogCategoriesAsync(string userName) {
            bizapps_test.MVC.AsmxCategoryServiceReference.GetBlogCategoriesRequest inValue = new bizapps_test.MVC.AsmxCategoryServiceReference.GetBlogCategoriesRequest();
            inValue.Body = new bizapps_test.MVC.AsmxCategoryServiceReference.GetBlogCategoriesRequestBody();
            inValue.Body.userName = userName;
            return ((bizapps_test.MVC.AsmxCategoryServiceReference.AsmxCategoryServiceSoap)(this)).GetBlogCategoriesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bizapps_test.MVC.AsmxCategoryServiceReference.GetCategoryByIdResponse bizapps_test.MVC.AsmxCategoryServiceReference.AsmxCategoryServiceSoap.GetCategoryById(bizapps_test.MVC.AsmxCategoryServiceReference.GetCategoryByIdRequest request) {
            return base.Channel.GetCategoryById(request);
        }
        
        public bizapps_test.MVC.AsmxCategoryServiceReference.CategorySoap GetCategoryById(int categoryId) {
            bizapps_test.MVC.AsmxCategoryServiceReference.GetCategoryByIdRequest inValue = new bizapps_test.MVC.AsmxCategoryServiceReference.GetCategoryByIdRequest();
            inValue.Body = new bizapps_test.MVC.AsmxCategoryServiceReference.GetCategoryByIdRequestBody();
            inValue.Body.categoryId = categoryId;
            bizapps_test.MVC.AsmxCategoryServiceReference.GetCategoryByIdResponse retVal = ((bizapps_test.MVC.AsmxCategoryServiceReference.AsmxCategoryServiceSoap)(this)).GetCategoryById(inValue);
            return retVal.Body.GetCategoryByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<bizapps_test.MVC.AsmxCategoryServiceReference.GetCategoryByIdResponse> bizapps_test.MVC.AsmxCategoryServiceReference.AsmxCategoryServiceSoap.GetCategoryByIdAsync(bizapps_test.MVC.AsmxCategoryServiceReference.GetCategoryByIdRequest request) {
            return base.Channel.GetCategoryByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<bizapps_test.MVC.AsmxCategoryServiceReference.GetCategoryByIdResponse> GetCategoryByIdAsync(int categoryId) {
            bizapps_test.MVC.AsmxCategoryServiceReference.GetCategoryByIdRequest inValue = new bizapps_test.MVC.AsmxCategoryServiceReference.GetCategoryByIdRequest();
            inValue.Body = new bizapps_test.MVC.AsmxCategoryServiceReference.GetCategoryByIdRequestBody();
            inValue.Body.categoryId = categoryId;
            return ((bizapps_test.MVC.AsmxCategoryServiceReference.AsmxCategoryServiceSoap)(this)).GetCategoryByIdAsync(inValue);
        }
    }
}
