//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bizapps_test.MVC.WcfCommentServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CommentDC", Namespace="http://schemas.datacontract.org/2004/07/bizapps_test.SL.Wcf_Services.DataContract" +
        "s")]
    [System.SerializableAttribute()]
    public partial class CommentDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ParentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PostIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CommentText {
            get {
                return this.CommentTextField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentTextField, value) != true)) {
                    this.CommentTextField = value;
                    this.RaisePropertyChanged("CommentText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreationDate {
            get {
                return this.CreationDateField;
            }
            set {
                if ((this.CreationDateField.Equals(value) != true)) {
                    this.CreationDateField = value;
                    this.RaisePropertyChanged("CreationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ParentId {
            get {
                return this.ParentIdField;
            }
            set {
                if ((this.ParentIdField.Equals(value) != true)) {
                    this.ParentIdField = value;
                    this.RaisePropertyChanged("ParentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PostId {
            get {
                return this.PostIdField;
            }
            set {
                if ((this.PostIdField.Equals(value) != true)) {
                    this.PostIdField = value;
                    this.RaisePropertyChanged("PostId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WcfCommentServiceReference.IWcfCommentService")]
    public interface IWcfCommentService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfCommentService/CreateComment", ReplyAction="http://tempuri.org/IWcfCommentService/CreateCommentResponse")]
        int CreateComment(bizapps_test.MVC.WcfCommentServiceReference.CommentDC commentDC, int postId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfCommentService/CreateComment", ReplyAction="http://tempuri.org/IWcfCommentService/CreateCommentResponse")]
        System.Threading.Tasks.Task<int> CreateCommentAsync(bizapps_test.MVC.WcfCommentServiceReference.CommentDC commentDC, int postId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfCommentService/UpdateComment", ReplyAction="http://tempuri.org/IWcfCommentService/UpdateCommentResponse")]
        int UpdateComment(bizapps_test.MVC.WcfCommentServiceReference.CommentDC commentDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfCommentService/UpdateComment", ReplyAction="http://tempuri.org/IWcfCommentService/UpdateCommentResponse")]
        System.Threading.Tasks.Task<int> UpdateCommentAsync(bizapps_test.MVC.WcfCommentServiceReference.CommentDC commentDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfCommentService/DeleteComment", ReplyAction="http://tempuri.org/IWcfCommentService/DeleteCommentResponse")]
        int DeleteComment(bizapps_test.MVC.WcfCommentServiceReference.CommentDC commentDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfCommentService/DeleteComment", ReplyAction="http://tempuri.org/IWcfCommentService/DeleteCommentResponse")]
        System.Threading.Tasks.Task<int> DeleteCommentAsync(bizapps_test.MVC.WcfCommentServiceReference.CommentDC commentDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfCommentService/GetIndependentComments", ReplyAction="http://tempuri.org/IWcfCommentService/GetIndependentCommentsResponse")]
        bizapps_test.MVC.WcfCommentServiceReference.CommentDC[] GetIndependentComments(int postId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfCommentService/GetIndependentComments", ReplyAction="http://tempuri.org/IWcfCommentService/GetIndependentCommentsResponse")]
        System.Threading.Tasks.Task<bizapps_test.MVC.WcfCommentServiceReference.CommentDC[]> GetIndependentCommentsAsync(int postId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfCommentService/GetCommentAnswers", ReplyAction="http://tempuri.org/IWcfCommentService/GetCommentAnswersResponse")]
        bizapps_test.MVC.WcfCommentServiceReference.CommentDC[] GetCommentAnswers(int commentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfCommentService/GetCommentAnswers", ReplyAction="http://tempuri.org/IWcfCommentService/GetCommentAnswersResponse")]
        System.Threading.Tasks.Task<bizapps_test.MVC.WcfCommentServiceReference.CommentDC[]> GetCommentAnswersAsync(int commentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfCommentService/GetComment", ReplyAction="http://tempuri.org/IWcfCommentService/GetCommentResponse")]
        bizapps_test.MVC.WcfCommentServiceReference.CommentDC GetComment(int commentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfCommentService/GetComment", ReplyAction="http://tempuri.org/IWcfCommentService/GetCommentResponse")]
        System.Threading.Tasks.Task<bizapps_test.MVC.WcfCommentServiceReference.CommentDC> GetCommentAsync(int commentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfCommentService/HaveMoreThanFourLevels", ReplyAction="http://tempuri.org/IWcfCommentService/HaveMoreThanFourLevelsResponse")]
        bool HaveMoreThanFourLevels(bizapps_test.MVC.WcfCommentServiceReference.CommentDC commentDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfCommentService/HaveMoreThanFourLevels", ReplyAction="http://tempuri.org/IWcfCommentService/HaveMoreThanFourLevelsResponse")]
        System.Threading.Tasks.Task<bool> HaveMoreThanFourLevelsAsync(bizapps_test.MVC.WcfCommentServiceReference.CommentDC commentDC);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWcfCommentServiceChannel : bizapps_test.MVC.WcfCommentServiceReference.IWcfCommentService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WcfCommentServiceClient : System.ServiceModel.ClientBase<bizapps_test.MVC.WcfCommentServiceReference.IWcfCommentService>, bizapps_test.MVC.WcfCommentServiceReference.IWcfCommentService {
        
        public WcfCommentServiceClient() {
        }
        
        public WcfCommentServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WcfCommentServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WcfCommentServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WcfCommentServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int CreateComment(bizapps_test.MVC.WcfCommentServiceReference.CommentDC commentDC, int postId) {
            return base.Channel.CreateComment(commentDC, postId);
        }
        
        public System.Threading.Tasks.Task<int> CreateCommentAsync(bizapps_test.MVC.WcfCommentServiceReference.CommentDC commentDC, int postId) {
            return base.Channel.CreateCommentAsync(commentDC, postId);
        }
        
        public int UpdateComment(bizapps_test.MVC.WcfCommentServiceReference.CommentDC commentDC) {
            return base.Channel.UpdateComment(commentDC);
        }
        
        public System.Threading.Tasks.Task<int> UpdateCommentAsync(bizapps_test.MVC.WcfCommentServiceReference.CommentDC commentDC) {
            return base.Channel.UpdateCommentAsync(commentDC);
        }
        
        public int DeleteComment(bizapps_test.MVC.WcfCommentServiceReference.CommentDC commentDC) {
            return base.Channel.DeleteComment(commentDC);
        }
        
        public System.Threading.Tasks.Task<int> DeleteCommentAsync(bizapps_test.MVC.WcfCommentServiceReference.CommentDC commentDC) {
            return base.Channel.DeleteCommentAsync(commentDC);
        }
        
        public bizapps_test.MVC.WcfCommentServiceReference.CommentDC[] GetIndependentComments(int postId) {
            return base.Channel.GetIndependentComments(postId);
        }
        
        public System.Threading.Tasks.Task<bizapps_test.MVC.WcfCommentServiceReference.CommentDC[]> GetIndependentCommentsAsync(int postId) {
            return base.Channel.GetIndependentCommentsAsync(postId);
        }
        
        public bizapps_test.MVC.WcfCommentServiceReference.CommentDC[] GetCommentAnswers(int commentId) {
            return base.Channel.GetCommentAnswers(commentId);
        }
        
        public System.Threading.Tasks.Task<bizapps_test.MVC.WcfCommentServiceReference.CommentDC[]> GetCommentAnswersAsync(int commentId) {
            return base.Channel.GetCommentAnswersAsync(commentId);
        }
        
        public bizapps_test.MVC.WcfCommentServiceReference.CommentDC GetComment(int commentId) {
            return base.Channel.GetComment(commentId);
        }
        
        public System.Threading.Tasks.Task<bizapps_test.MVC.WcfCommentServiceReference.CommentDC> GetCommentAsync(int commentId) {
            return base.Channel.GetCommentAsync(commentId);
        }
        
        public bool HaveMoreThanFourLevels(bizapps_test.MVC.WcfCommentServiceReference.CommentDC commentDC) {
            return base.Channel.HaveMoreThanFourLevels(commentDC);
        }
        
        public System.Threading.Tasks.Task<bool> HaveMoreThanFourLevelsAsync(bizapps_test.MVC.WcfCommentServiceReference.CommentDC commentDC) {
            return base.Channel.HaveMoreThanFourLevelsAsync(commentDC);
        }
    }
}
