//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bizapps_test.MVC.AsmxCommentServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CommentSoap", Namespace="http://comments.org/")]
    [System.SerializableAttribute()]
    public partial class CommentSoap : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        private System.DateTime CreationDateField;
        
        private int ParentIdField;
        
        private int PostIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CommentText {
            get {
                return this.CommentTextField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentTextField, value) != true)) {
                    this.CommentTextField = value;
                    this.RaisePropertyChanged("CommentText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime CreationDate {
            get {
                return this.CreationDateField;
            }
            set {
                if ((this.CreationDateField.Equals(value) != true)) {
                    this.CreationDateField = value;
                    this.RaisePropertyChanged("CreationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int ParentId {
            get {
                return this.ParentIdField;
            }
            set {
                if ((this.ParentIdField.Equals(value) != true)) {
                    this.ParentIdField = value;
                    this.RaisePropertyChanged("ParentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int PostId {
            get {
                return this.PostIdField;
            }
            set {
                if ((this.PostIdField.Equals(value) != true)) {
                    this.PostIdField = value;
                    this.RaisePropertyChanged("PostId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://comments.org/", ConfigurationName="AsmxCommentServiceReference.AsmxCommentServiceSoap")]
    public interface AsmxCommentServiceSoap {
        
        // CODEGEN: Generating message contract since element name commentSoap from namespace http://comments.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://comments.org/CreateComment", ReplyAction="*")]
        bizapps_test.MVC.AsmxCommentServiceReference.CreateCommentResponse CreateComment(bizapps_test.MVC.AsmxCommentServiceReference.CreateCommentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://comments.org/CreateComment", ReplyAction="*")]
        System.Threading.Tasks.Task<bizapps_test.MVC.AsmxCommentServiceReference.CreateCommentResponse> CreateCommentAsync(bizapps_test.MVC.AsmxCommentServiceReference.CreateCommentRequest request);
        
        // CODEGEN: Generating message contract since element name commentSoap from namespace http://comments.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://comments.org/UpdateComment", ReplyAction="*")]
        bizapps_test.MVC.AsmxCommentServiceReference.UpdateCommentResponse UpdateComment(bizapps_test.MVC.AsmxCommentServiceReference.UpdateCommentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://comments.org/UpdateComment", ReplyAction="*")]
        System.Threading.Tasks.Task<bizapps_test.MVC.AsmxCommentServiceReference.UpdateCommentResponse> UpdateCommentAsync(bizapps_test.MVC.AsmxCommentServiceReference.UpdateCommentRequest request);
        
        // CODEGEN: Generating message contract since element name commentSoap from namespace http://comments.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://comments.org/DeleteComment", ReplyAction="*")]
        bizapps_test.MVC.AsmxCommentServiceReference.DeleteCommentResponse DeleteComment(bizapps_test.MVC.AsmxCommentServiceReference.DeleteCommentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://comments.org/DeleteComment", ReplyAction="*")]
        System.Threading.Tasks.Task<bizapps_test.MVC.AsmxCommentServiceReference.DeleteCommentResponse> DeleteCommentAsync(bizapps_test.MVC.AsmxCommentServiceReference.DeleteCommentRequest request);
        
        // CODEGEN: Generating message contract since element name GetIndependentCommentsResult from namespace http://comments.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://comments.org/GetIndependentComments", ReplyAction="*")]
        bizapps_test.MVC.AsmxCommentServiceReference.GetIndependentCommentsResponse GetIndependentComments(bizapps_test.MVC.AsmxCommentServiceReference.GetIndependentCommentsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://comments.org/GetIndependentComments", ReplyAction="*")]
        System.Threading.Tasks.Task<bizapps_test.MVC.AsmxCommentServiceReference.GetIndependentCommentsResponse> GetIndependentCommentsAsync(bizapps_test.MVC.AsmxCommentServiceReference.GetIndependentCommentsRequest request);
        
        // CODEGEN: Generating message contract since element name GetCommentAnswersResult from namespace http://comments.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://comments.org/GetCommentAnswers", ReplyAction="*")]
        bizapps_test.MVC.AsmxCommentServiceReference.GetCommentAnswersResponse GetCommentAnswers(bizapps_test.MVC.AsmxCommentServiceReference.GetCommentAnswersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://comments.org/GetCommentAnswers", ReplyAction="*")]
        System.Threading.Tasks.Task<bizapps_test.MVC.AsmxCommentServiceReference.GetCommentAnswersResponse> GetCommentAnswersAsync(bizapps_test.MVC.AsmxCommentServiceReference.GetCommentAnswersRequest request);
        
        // CODEGEN: Generating message contract since element name GetCommentResult from namespace http://comments.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://comments.org/GetComment", ReplyAction="*")]
        bizapps_test.MVC.AsmxCommentServiceReference.GetCommentResponse GetComment(bizapps_test.MVC.AsmxCommentServiceReference.GetCommentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://comments.org/GetComment", ReplyAction="*")]
        System.Threading.Tasks.Task<bizapps_test.MVC.AsmxCommentServiceReference.GetCommentResponse> GetCommentAsync(bizapps_test.MVC.AsmxCommentServiceReference.GetCommentRequest request);
        
        // CODEGEN: Generating message contract since element name commentSoap from namespace http://comments.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://comments.org/HaveMoreThanFourLevels", ReplyAction="*")]
        bizapps_test.MVC.AsmxCommentServiceReference.HaveMoreThanFourLevelsResponse HaveMoreThanFourLevels(bizapps_test.MVC.AsmxCommentServiceReference.HaveMoreThanFourLevelsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://comments.org/HaveMoreThanFourLevels", ReplyAction="*")]
        System.Threading.Tasks.Task<bizapps_test.MVC.AsmxCommentServiceReference.HaveMoreThanFourLevelsResponse> HaveMoreThanFourLevelsAsync(bizapps_test.MVC.AsmxCommentServiceReference.HaveMoreThanFourLevelsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateCommentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateComment", Namespace="http://comments.org/", Order=0)]
        public bizapps_test.MVC.AsmxCommentServiceReference.CreateCommentRequestBody Body;
        
        public CreateCommentRequest() {
        }
        
        public CreateCommentRequest(bizapps_test.MVC.AsmxCommentServiceReference.CreateCommentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://comments.org/")]
    public partial class CreateCommentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public bizapps_test.MVC.AsmxCommentServiceReference.CommentSoap commentSoap;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int postId;
        
        public CreateCommentRequestBody() {
        }
        
        public CreateCommentRequestBody(bizapps_test.MVC.AsmxCommentServiceReference.CommentSoap commentSoap, int postId) {
            this.commentSoap = commentSoap;
            this.postId = postId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateCommentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateCommentResponse", Namespace="http://comments.org/", Order=0)]
        public bizapps_test.MVC.AsmxCommentServiceReference.CreateCommentResponseBody Body;
        
        public CreateCommentResponse() {
        }
        
        public CreateCommentResponse(bizapps_test.MVC.AsmxCommentServiceReference.CreateCommentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://comments.org/")]
    public partial class CreateCommentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int CreateCommentResult;
        
        public CreateCommentResponseBody() {
        }
        
        public CreateCommentResponseBody(int CreateCommentResult) {
            this.CreateCommentResult = CreateCommentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateCommentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateComment", Namespace="http://comments.org/", Order=0)]
        public bizapps_test.MVC.AsmxCommentServiceReference.UpdateCommentRequestBody Body;
        
        public UpdateCommentRequest() {
        }
        
        public UpdateCommentRequest(bizapps_test.MVC.AsmxCommentServiceReference.UpdateCommentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://comments.org/")]
    public partial class UpdateCommentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public bizapps_test.MVC.AsmxCommentServiceReference.CommentSoap commentSoap;
        
        public UpdateCommentRequestBody() {
        }
        
        public UpdateCommentRequestBody(bizapps_test.MVC.AsmxCommentServiceReference.CommentSoap commentSoap) {
            this.commentSoap = commentSoap;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateCommentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateCommentResponse", Namespace="http://comments.org/", Order=0)]
        public bizapps_test.MVC.AsmxCommentServiceReference.UpdateCommentResponseBody Body;
        
        public UpdateCommentResponse() {
        }
        
        public UpdateCommentResponse(bizapps_test.MVC.AsmxCommentServiceReference.UpdateCommentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://comments.org/")]
    public partial class UpdateCommentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UpdateCommentResult;
        
        public UpdateCommentResponseBody() {
        }
        
        public UpdateCommentResponseBody(int UpdateCommentResult) {
            this.UpdateCommentResult = UpdateCommentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteCommentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteComment", Namespace="http://comments.org/", Order=0)]
        public bizapps_test.MVC.AsmxCommentServiceReference.DeleteCommentRequestBody Body;
        
        public DeleteCommentRequest() {
        }
        
        public DeleteCommentRequest(bizapps_test.MVC.AsmxCommentServiceReference.DeleteCommentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://comments.org/")]
    public partial class DeleteCommentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public bizapps_test.MVC.AsmxCommentServiceReference.CommentSoap commentSoap;
        
        public DeleteCommentRequestBody() {
        }
        
        public DeleteCommentRequestBody(bizapps_test.MVC.AsmxCommentServiceReference.CommentSoap commentSoap) {
            this.commentSoap = commentSoap;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteCommentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteCommentResponse", Namespace="http://comments.org/", Order=0)]
        public bizapps_test.MVC.AsmxCommentServiceReference.DeleteCommentResponseBody Body;
        
        public DeleteCommentResponse() {
        }
        
        public DeleteCommentResponse(bizapps_test.MVC.AsmxCommentServiceReference.DeleteCommentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://comments.org/")]
    public partial class DeleteCommentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int DeleteCommentResult;
        
        public DeleteCommentResponseBody() {
        }
        
        public DeleteCommentResponseBody(int DeleteCommentResult) {
            this.DeleteCommentResult = DeleteCommentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetIndependentCommentsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetIndependentComments", Namespace="http://comments.org/", Order=0)]
        public bizapps_test.MVC.AsmxCommentServiceReference.GetIndependentCommentsRequestBody Body;
        
        public GetIndependentCommentsRequest() {
        }
        
        public GetIndependentCommentsRequest(bizapps_test.MVC.AsmxCommentServiceReference.GetIndependentCommentsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://comments.org/")]
    public partial class GetIndependentCommentsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int postId;
        
        public GetIndependentCommentsRequestBody() {
        }
        
        public GetIndependentCommentsRequestBody(int postId) {
            this.postId = postId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetIndependentCommentsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetIndependentCommentsResponse", Namespace="http://comments.org/", Order=0)]
        public bizapps_test.MVC.AsmxCommentServiceReference.GetIndependentCommentsResponseBody Body;
        
        public GetIndependentCommentsResponse() {
        }
        
        public GetIndependentCommentsResponse(bizapps_test.MVC.AsmxCommentServiceReference.GetIndependentCommentsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://comments.org/")]
    public partial class GetIndependentCommentsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public bizapps_test.MVC.AsmxCommentServiceReference.CommentSoap[] GetIndependentCommentsResult;
        
        public GetIndependentCommentsResponseBody() {
        }
        
        public GetIndependentCommentsResponseBody(bizapps_test.MVC.AsmxCommentServiceReference.CommentSoap[] GetIndependentCommentsResult) {
            this.GetIndependentCommentsResult = GetIndependentCommentsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCommentAnswersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCommentAnswers", Namespace="http://comments.org/", Order=0)]
        public bizapps_test.MVC.AsmxCommentServiceReference.GetCommentAnswersRequestBody Body;
        
        public GetCommentAnswersRequest() {
        }
        
        public GetCommentAnswersRequest(bizapps_test.MVC.AsmxCommentServiceReference.GetCommentAnswersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://comments.org/")]
    public partial class GetCommentAnswersRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int commentId;
        
        public GetCommentAnswersRequestBody() {
        }
        
        public GetCommentAnswersRequestBody(int commentId) {
            this.commentId = commentId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCommentAnswersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCommentAnswersResponse", Namespace="http://comments.org/", Order=0)]
        public bizapps_test.MVC.AsmxCommentServiceReference.GetCommentAnswersResponseBody Body;
        
        public GetCommentAnswersResponse() {
        }
        
        public GetCommentAnswersResponse(bizapps_test.MVC.AsmxCommentServiceReference.GetCommentAnswersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://comments.org/")]
    public partial class GetCommentAnswersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public bizapps_test.MVC.AsmxCommentServiceReference.CommentSoap[] GetCommentAnswersResult;
        
        public GetCommentAnswersResponseBody() {
        }
        
        public GetCommentAnswersResponseBody(bizapps_test.MVC.AsmxCommentServiceReference.CommentSoap[] GetCommentAnswersResult) {
            this.GetCommentAnswersResult = GetCommentAnswersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCommentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetComment", Namespace="http://comments.org/", Order=0)]
        public bizapps_test.MVC.AsmxCommentServiceReference.GetCommentRequestBody Body;
        
        public GetCommentRequest() {
        }
        
        public GetCommentRequest(bizapps_test.MVC.AsmxCommentServiceReference.GetCommentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://comments.org/")]
    public partial class GetCommentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int commentId;
        
        public GetCommentRequestBody() {
        }
        
        public GetCommentRequestBody(int commentId) {
            this.commentId = commentId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCommentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCommentResponse", Namespace="http://comments.org/", Order=0)]
        public bizapps_test.MVC.AsmxCommentServiceReference.GetCommentResponseBody Body;
        
        public GetCommentResponse() {
        }
        
        public GetCommentResponse(bizapps_test.MVC.AsmxCommentServiceReference.GetCommentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://comments.org/")]
    public partial class GetCommentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public bizapps_test.MVC.AsmxCommentServiceReference.CommentSoap GetCommentResult;
        
        public GetCommentResponseBody() {
        }
        
        public GetCommentResponseBody(bizapps_test.MVC.AsmxCommentServiceReference.CommentSoap GetCommentResult) {
            this.GetCommentResult = GetCommentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HaveMoreThanFourLevelsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HaveMoreThanFourLevels", Namespace="http://comments.org/", Order=0)]
        public bizapps_test.MVC.AsmxCommentServiceReference.HaveMoreThanFourLevelsRequestBody Body;
        
        public HaveMoreThanFourLevelsRequest() {
        }
        
        public HaveMoreThanFourLevelsRequest(bizapps_test.MVC.AsmxCommentServiceReference.HaveMoreThanFourLevelsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://comments.org/")]
    public partial class HaveMoreThanFourLevelsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public bizapps_test.MVC.AsmxCommentServiceReference.CommentSoap commentSoap;
        
        public HaveMoreThanFourLevelsRequestBody() {
        }
        
        public HaveMoreThanFourLevelsRequestBody(bizapps_test.MVC.AsmxCommentServiceReference.CommentSoap commentSoap) {
            this.commentSoap = commentSoap;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HaveMoreThanFourLevelsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HaveMoreThanFourLevelsResponse", Namespace="http://comments.org/", Order=0)]
        public bizapps_test.MVC.AsmxCommentServiceReference.HaveMoreThanFourLevelsResponseBody Body;
        
        public HaveMoreThanFourLevelsResponse() {
        }
        
        public HaveMoreThanFourLevelsResponse(bizapps_test.MVC.AsmxCommentServiceReference.HaveMoreThanFourLevelsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://comments.org/")]
    public partial class HaveMoreThanFourLevelsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool HaveMoreThanFourLevelsResult;
        
        public HaveMoreThanFourLevelsResponseBody() {
        }
        
        public HaveMoreThanFourLevelsResponseBody(bool HaveMoreThanFourLevelsResult) {
            this.HaveMoreThanFourLevelsResult = HaveMoreThanFourLevelsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AsmxCommentServiceSoapChannel : bizapps_test.MVC.AsmxCommentServiceReference.AsmxCommentServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AsmxCommentServiceSoapClient : System.ServiceModel.ClientBase<bizapps_test.MVC.AsmxCommentServiceReference.AsmxCommentServiceSoap>, bizapps_test.MVC.AsmxCommentServiceReference.AsmxCommentServiceSoap {
        
        public AsmxCommentServiceSoapClient() {
        }
        
        public AsmxCommentServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AsmxCommentServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AsmxCommentServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AsmxCommentServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bizapps_test.MVC.AsmxCommentServiceReference.CreateCommentResponse bizapps_test.MVC.AsmxCommentServiceReference.AsmxCommentServiceSoap.CreateComment(bizapps_test.MVC.AsmxCommentServiceReference.CreateCommentRequest request) {
            return base.Channel.CreateComment(request);
        }
        
        public int CreateComment(bizapps_test.MVC.AsmxCommentServiceReference.CommentSoap commentSoap, int postId) {
            bizapps_test.MVC.AsmxCommentServiceReference.CreateCommentRequest inValue = new bizapps_test.MVC.AsmxCommentServiceReference.CreateCommentRequest();
            inValue.Body = new bizapps_test.MVC.AsmxCommentServiceReference.CreateCommentRequestBody();
            inValue.Body.commentSoap = commentSoap;
            inValue.Body.postId = postId;
            bizapps_test.MVC.AsmxCommentServiceReference.CreateCommentResponse retVal = ((bizapps_test.MVC.AsmxCommentServiceReference.AsmxCommentServiceSoap)(this)).CreateComment(inValue);
            return retVal.Body.CreateCommentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<bizapps_test.MVC.AsmxCommentServiceReference.CreateCommentResponse> bizapps_test.MVC.AsmxCommentServiceReference.AsmxCommentServiceSoap.CreateCommentAsync(bizapps_test.MVC.AsmxCommentServiceReference.CreateCommentRequest request) {
            return base.Channel.CreateCommentAsync(request);
        }
        
        public System.Threading.Tasks.Task<bizapps_test.MVC.AsmxCommentServiceReference.CreateCommentResponse> CreateCommentAsync(bizapps_test.MVC.AsmxCommentServiceReference.CommentSoap commentSoap, int postId) {
            bizapps_test.MVC.AsmxCommentServiceReference.CreateCommentRequest inValue = new bizapps_test.MVC.AsmxCommentServiceReference.CreateCommentRequest();
            inValue.Body = new bizapps_test.MVC.AsmxCommentServiceReference.CreateCommentRequestBody();
            inValue.Body.commentSoap = commentSoap;
            inValue.Body.postId = postId;
            return ((bizapps_test.MVC.AsmxCommentServiceReference.AsmxCommentServiceSoap)(this)).CreateCommentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bizapps_test.MVC.AsmxCommentServiceReference.UpdateCommentResponse bizapps_test.MVC.AsmxCommentServiceReference.AsmxCommentServiceSoap.UpdateComment(bizapps_test.MVC.AsmxCommentServiceReference.UpdateCommentRequest request) {
            return base.Channel.UpdateComment(request);
        }
        
        public int UpdateComment(bizapps_test.MVC.AsmxCommentServiceReference.CommentSoap commentSoap) {
            bizapps_test.MVC.AsmxCommentServiceReference.UpdateCommentRequest inValue = new bizapps_test.MVC.AsmxCommentServiceReference.UpdateCommentRequest();
            inValue.Body = new bizapps_test.MVC.AsmxCommentServiceReference.UpdateCommentRequestBody();
            inValue.Body.commentSoap = commentSoap;
            bizapps_test.MVC.AsmxCommentServiceReference.UpdateCommentResponse retVal = ((bizapps_test.MVC.AsmxCommentServiceReference.AsmxCommentServiceSoap)(this)).UpdateComment(inValue);
            return retVal.Body.UpdateCommentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<bizapps_test.MVC.AsmxCommentServiceReference.UpdateCommentResponse> bizapps_test.MVC.AsmxCommentServiceReference.AsmxCommentServiceSoap.UpdateCommentAsync(bizapps_test.MVC.AsmxCommentServiceReference.UpdateCommentRequest request) {
            return base.Channel.UpdateCommentAsync(request);
        }
        
        public System.Threading.Tasks.Task<bizapps_test.MVC.AsmxCommentServiceReference.UpdateCommentResponse> UpdateCommentAsync(bizapps_test.MVC.AsmxCommentServiceReference.CommentSoap commentSoap) {
            bizapps_test.MVC.AsmxCommentServiceReference.UpdateCommentRequest inValue = new bizapps_test.MVC.AsmxCommentServiceReference.UpdateCommentRequest();
            inValue.Body = new bizapps_test.MVC.AsmxCommentServiceReference.UpdateCommentRequestBody();
            inValue.Body.commentSoap = commentSoap;
            return ((bizapps_test.MVC.AsmxCommentServiceReference.AsmxCommentServiceSoap)(this)).UpdateCommentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bizapps_test.MVC.AsmxCommentServiceReference.DeleteCommentResponse bizapps_test.MVC.AsmxCommentServiceReference.AsmxCommentServiceSoap.DeleteComment(bizapps_test.MVC.AsmxCommentServiceReference.DeleteCommentRequest request) {
            return base.Channel.DeleteComment(request);
        }
        
        public int DeleteComment(bizapps_test.MVC.AsmxCommentServiceReference.CommentSoap commentSoap) {
            bizapps_test.MVC.AsmxCommentServiceReference.DeleteCommentRequest inValue = new bizapps_test.MVC.AsmxCommentServiceReference.DeleteCommentRequest();
            inValue.Body = new bizapps_test.MVC.AsmxCommentServiceReference.DeleteCommentRequestBody();
            inValue.Body.commentSoap = commentSoap;
            bizapps_test.MVC.AsmxCommentServiceReference.DeleteCommentResponse retVal = ((bizapps_test.MVC.AsmxCommentServiceReference.AsmxCommentServiceSoap)(this)).DeleteComment(inValue);
            return retVal.Body.DeleteCommentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<bizapps_test.MVC.AsmxCommentServiceReference.DeleteCommentResponse> bizapps_test.MVC.AsmxCommentServiceReference.AsmxCommentServiceSoap.DeleteCommentAsync(bizapps_test.MVC.AsmxCommentServiceReference.DeleteCommentRequest request) {
            return base.Channel.DeleteCommentAsync(request);
        }
        
        public System.Threading.Tasks.Task<bizapps_test.MVC.AsmxCommentServiceReference.DeleteCommentResponse> DeleteCommentAsync(bizapps_test.MVC.AsmxCommentServiceReference.CommentSoap commentSoap) {
            bizapps_test.MVC.AsmxCommentServiceReference.DeleteCommentRequest inValue = new bizapps_test.MVC.AsmxCommentServiceReference.DeleteCommentRequest();
            inValue.Body = new bizapps_test.MVC.AsmxCommentServiceReference.DeleteCommentRequestBody();
            inValue.Body.commentSoap = commentSoap;
            return ((bizapps_test.MVC.AsmxCommentServiceReference.AsmxCommentServiceSoap)(this)).DeleteCommentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bizapps_test.MVC.AsmxCommentServiceReference.GetIndependentCommentsResponse bizapps_test.MVC.AsmxCommentServiceReference.AsmxCommentServiceSoap.GetIndependentComments(bizapps_test.MVC.AsmxCommentServiceReference.GetIndependentCommentsRequest request) {
            return base.Channel.GetIndependentComments(request);
        }
        
        public bizapps_test.MVC.AsmxCommentServiceReference.CommentSoap[] GetIndependentComments(int postId) {
            bizapps_test.MVC.AsmxCommentServiceReference.GetIndependentCommentsRequest inValue = new bizapps_test.MVC.AsmxCommentServiceReference.GetIndependentCommentsRequest();
            inValue.Body = new bizapps_test.MVC.AsmxCommentServiceReference.GetIndependentCommentsRequestBody();
            inValue.Body.postId = postId;
            bizapps_test.MVC.AsmxCommentServiceReference.GetIndependentCommentsResponse retVal = ((bizapps_test.MVC.AsmxCommentServiceReference.AsmxCommentServiceSoap)(this)).GetIndependentComments(inValue);
            return retVal.Body.GetIndependentCommentsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<bizapps_test.MVC.AsmxCommentServiceReference.GetIndependentCommentsResponse> bizapps_test.MVC.AsmxCommentServiceReference.AsmxCommentServiceSoap.GetIndependentCommentsAsync(bizapps_test.MVC.AsmxCommentServiceReference.GetIndependentCommentsRequest request) {
            return base.Channel.GetIndependentCommentsAsync(request);
        }
        
        public System.Threading.Tasks.Task<bizapps_test.MVC.AsmxCommentServiceReference.GetIndependentCommentsResponse> GetIndependentCommentsAsync(int postId) {
            bizapps_test.MVC.AsmxCommentServiceReference.GetIndependentCommentsRequest inValue = new bizapps_test.MVC.AsmxCommentServiceReference.GetIndependentCommentsRequest();
            inValue.Body = new bizapps_test.MVC.AsmxCommentServiceReference.GetIndependentCommentsRequestBody();
            inValue.Body.postId = postId;
            return ((bizapps_test.MVC.AsmxCommentServiceReference.AsmxCommentServiceSoap)(this)).GetIndependentCommentsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bizapps_test.MVC.AsmxCommentServiceReference.GetCommentAnswersResponse bizapps_test.MVC.AsmxCommentServiceReference.AsmxCommentServiceSoap.GetCommentAnswers(bizapps_test.MVC.AsmxCommentServiceReference.GetCommentAnswersRequest request) {
            return base.Channel.GetCommentAnswers(request);
        }
        
        public bizapps_test.MVC.AsmxCommentServiceReference.CommentSoap[] GetCommentAnswers(int commentId) {
            bizapps_test.MVC.AsmxCommentServiceReference.GetCommentAnswersRequest inValue = new bizapps_test.MVC.AsmxCommentServiceReference.GetCommentAnswersRequest();
            inValue.Body = new bizapps_test.MVC.AsmxCommentServiceReference.GetCommentAnswersRequestBody();
            inValue.Body.commentId = commentId;
            bizapps_test.MVC.AsmxCommentServiceReference.GetCommentAnswersResponse retVal = ((bizapps_test.MVC.AsmxCommentServiceReference.AsmxCommentServiceSoap)(this)).GetCommentAnswers(inValue);
            return retVal.Body.GetCommentAnswersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<bizapps_test.MVC.AsmxCommentServiceReference.GetCommentAnswersResponse> bizapps_test.MVC.AsmxCommentServiceReference.AsmxCommentServiceSoap.GetCommentAnswersAsync(bizapps_test.MVC.AsmxCommentServiceReference.GetCommentAnswersRequest request) {
            return base.Channel.GetCommentAnswersAsync(request);
        }
        
        public System.Threading.Tasks.Task<bizapps_test.MVC.AsmxCommentServiceReference.GetCommentAnswersResponse> GetCommentAnswersAsync(int commentId) {
            bizapps_test.MVC.AsmxCommentServiceReference.GetCommentAnswersRequest inValue = new bizapps_test.MVC.AsmxCommentServiceReference.GetCommentAnswersRequest();
            inValue.Body = new bizapps_test.MVC.AsmxCommentServiceReference.GetCommentAnswersRequestBody();
            inValue.Body.commentId = commentId;
            return ((bizapps_test.MVC.AsmxCommentServiceReference.AsmxCommentServiceSoap)(this)).GetCommentAnswersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bizapps_test.MVC.AsmxCommentServiceReference.GetCommentResponse bizapps_test.MVC.AsmxCommentServiceReference.AsmxCommentServiceSoap.GetComment(bizapps_test.MVC.AsmxCommentServiceReference.GetCommentRequest request) {
            return base.Channel.GetComment(request);
        }
        
        public bizapps_test.MVC.AsmxCommentServiceReference.CommentSoap GetComment(int commentId) {
            bizapps_test.MVC.AsmxCommentServiceReference.GetCommentRequest inValue = new bizapps_test.MVC.AsmxCommentServiceReference.GetCommentRequest();
            inValue.Body = new bizapps_test.MVC.AsmxCommentServiceReference.GetCommentRequestBody();
            inValue.Body.commentId = commentId;
            bizapps_test.MVC.AsmxCommentServiceReference.GetCommentResponse retVal = ((bizapps_test.MVC.AsmxCommentServiceReference.AsmxCommentServiceSoap)(this)).GetComment(inValue);
            return retVal.Body.GetCommentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<bizapps_test.MVC.AsmxCommentServiceReference.GetCommentResponse> bizapps_test.MVC.AsmxCommentServiceReference.AsmxCommentServiceSoap.GetCommentAsync(bizapps_test.MVC.AsmxCommentServiceReference.GetCommentRequest request) {
            return base.Channel.GetCommentAsync(request);
        }
        
        public System.Threading.Tasks.Task<bizapps_test.MVC.AsmxCommentServiceReference.GetCommentResponse> GetCommentAsync(int commentId) {
            bizapps_test.MVC.AsmxCommentServiceReference.GetCommentRequest inValue = new bizapps_test.MVC.AsmxCommentServiceReference.GetCommentRequest();
            inValue.Body = new bizapps_test.MVC.AsmxCommentServiceReference.GetCommentRequestBody();
            inValue.Body.commentId = commentId;
            return ((bizapps_test.MVC.AsmxCommentServiceReference.AsmxCommentServiceSoap)(this)).GetCommentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bizapps_test.MVC.AsmxCommentServiceReference.HaveMoreThanFourLevelsResponse bizapps_test.MVC.AsmxCommentServiceReference.AsmxCommentServiceSoap.HaveMoreThanFourLevels(bizapps_test.MVC.AsmxCommentServiceReference.HaveMoreThanFourLevelsRequest request) {
            return base.Channel.HaveMoreThanFourLevels(request);
        }
        
        public bool HaveMoreThanFourLevels(bizapps_test.MVC.AsmxCommentServiceReference.CommentSoap commentSoap) {
            bizapps_test.MVC.AsmxCommentServiceReference.HaveMoreThanFourLevelsRequest inValue = new bizapps_test.MVC.AsmxCommentServiceReference.HaveMoreThanFourLevelsRequest();
            inValue.Body = new bizapps_test.MVC.AsmxCommentServiceReference.HaveMoreThanFourLevelsRequestBody();
            inValue.Body.commentSoap = commentSoap;
            bizapps_test.MVC.AsmxCommentServiceReference.HaveMoreThanFourLevelsResponse retVal = ((bizapps_test.MVC.AsmxCommentServiceReference.AsmxCommentServiceSoap)(this)).HaveMoreThanFourLevels(inValue);
            return retVal.Body.HaveMoreThanFourLevelsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<bizapps_test.MVC.AsmxCommentServiceReference.HaveMoreThanFourLevelsResponse> bizapps_test.MVC.AsmxCommentServiceReference.AsmxCommentServiceSoap.HaveMoreThanFourLevelsAsync(bizapps_test.MVC.AsmxCommentServiceReference.HaveMoreThanFourLevelsRequest request) {
            return base.Channel.HaveMoreThanFourLevelsAsync(request);
        }
        
        public System.Threading.Tasks.Task<bizapps_test.MVC.AsmxCommentServiceReference.HaveMoreThanFourLevelsResponse> HaveMoreThanFourLevelsAsync(bizapps_test.MVC.AsmxCommentServiceReference.CommentSoap commentSoap) {
            bizapps_test.MVC.AsmxCommentServiceReference.HaveMoreThanFourLevelsRequest inValue = new bizapps_test.MVC.AsmxCommentServiceReference.HaveMoreThanFourLevelsRequest();
            inValue.Body = new bizapps_test.MVC.AsmxCommentServiceReference.HaveMoreThanFourLevelsRequestBody();
            inValue.Body.commentSoap = commentSoap;
            return ((bizapps_test.MVC.AsmxCommentServiceReference.AsmxCommentServiceSoap)(this)).HaveMoreThanFourLevelsAsync(inValue);
        }
    }
}
