//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bizapps_test.MVC.AsmxBlogUserServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BlogUserSoap", Namespace="http://bloguser.org/")]
    [System.SerializableAttribute()]
    public partial class BlogUserSoap : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserPasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BlogNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UserPassword {
            get {
                return this.UserPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.UserPasswordField, value) != true)) {
                    this.UserPasswordField = value;
                    this.RaisePropertyChanged("UserPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string BlogName {
            get {
                return this.BlogNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BlogNameField, value) != true)) {
                    this.BlogNameField = value;
                    this.RaisePropertyChanged("BlogName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://bloguser.org/", ConfigurationName="AsmxBlogUserServiceReference.AsmxBlogUserServiceSoap")]
    public interface AsmxBlogUserServiceSoap {
        
        // CODEGEN: Generating message contract since element name bloguserSoap from namespace http://bloguser.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://bloguser.org/CreateBlogUser", ReplyAction="*")]
        bizapps_test.MVC.AsmxBlogUserServiceReference.CreateBlogUserResponse CreateBlogUser(bizapps_test.MVC.AsmxBlogUserServiceReference.CreateBlogUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bloguser.org/CreateBlogUser", ReplyAction="*")]
        System.Threading.Tasks.Task<bizapps_test.MVC.AsmxBlogUserServiceReference.CreateBlogUserResponse> CreateBlogUserAsync(bizapps_test.MVC.AsmxBlogUserServiceReference.CreateBlogUserRequest request);
        
        // CODEGEN: Generating message contract since element name bloguserSoap from namespace http://bloguser.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://bloguser.org/UpdateBlogUser", ReplyAction="*")]
        bizapps_test.MVC.AsmxBlogUserServiceReference.UpdateBlogUserResponse UpdateBlogUser(bizapps_test.MVC.AsmxBlogUserServiceReference.UpdateBlogUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bloguser.org/UpdateBlogUser", ReplyAction="*")]
        System.Threading.Tasks.Task<bizapps_test.MVC.AsmxBlogUserServiceReference.UpdateBlogUserResponse> UpdateBlogUserAsync(bizapps_test.MVC.AsmxBlogUserServiceReference.UpdateBlogUserRequest request);
        
        // CODEGEN: Generating message contract since element name bloguserSoap from namespace http://bloguser.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://bloguser.org/DeleteBlogUser", ReplyAction="*")]
        bizapps_test.MVC.AsmxBlogUserServiceReference.DeleteBlogUserResponse DeleteBlogUser(bizapps_test.MVC.AsmxBlogUserServiceReference.DeleteBlogUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bloguser.org/DeleteBlogUser", ReplyAction="*")]
        System.Threading.Tasks.Task<bizapps_test.MVC.AsmxBlogUserServiceReference.DeleteBlogUserResponse> DeleteBlogUserAsync(bizapps_test.MVC.AsmxBlogUserServiceReference.DeleteBlogUserRequest request);
        
        // CODEGEN: Generating message contract since element name bloguserSoap from namespace http://bloguser.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://bloguser.org/ChangePassword", ReplyAction="*")]
        bizapps_test.MVC.AsmxBlogUserServiceReference.ChangePasswordResponse ChangePassword(bizapps_test.MVC.AsmxBlogUserServiceReference.ChangePasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bloguser.org/ChangePassword", ReplyAction="*")]
        System.Threading.Tasks.Task<bizapps_test.MVC.AsmxBlogUserServiceReference.ChangePasswordResponse> ChangePasswordAsync(bizapps_test.MVC.AsmxBlogUserServiceReference.ChangePasswordRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllUsersResult from namespace http://bloguser.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://bloguser.org/GetAllUsers", ReplyAction="*")]
        bizapps_test.MVC.AsmxBlogUserServiceReference.GetAllUsersResponse GetAllUsers(bizapps_test.MVC.AsmxBlogUserServiceReference.GetAllUsersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bloguser.org/GetAllUsers", ReplyAction="*")]
        System.Threading.Tasks.Task<bizapps_test.MVC.AsmxBlogUserServiceReference.GetAllUsersResponse> GetAllUsersAsync(bizapps_test.MVC.AsmxBlogUserServiceReference.GetAllUsersRequest request);
        
        // CODEGEN: Generating message contract since element name GetBlogUserByIdResult from namespace http://bloguser.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://bloguser.org/GetBlogUserById", ReplyAction="*")]
        bizapps_test.MVC.AsmxBlogUserServiceReference.GetBlogUserByIdResponse GetBlogUserById(bizapps_test.MVC.AsmxBlogUserServiceReference.GetBlogUserByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bloguser.org/GetBlogUserById", ReplyAction="*")]
        System.Threading.Tasks.Task<bizapps_test.MVC.AsmxBlogUserServiceReference.GetBlogUserByIdResponse> GetBlogUserByIdAsync(bizapps_test.MVC.AsmxBlogUserServiceReference.GetBlogUserByIdRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace http://bloguser.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://bloguser.org/GetBlogUserByName", ReplyAction="*")]
        bizapps_test.MVC.AsmxBlogUserServiceReference.GetBlogUserByNameResponse GetBlogUserByName(bizapps_test.MVC.AsmxBlogUserServiceReference.GetBlogUserByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bloguser.org/GetBlogUserByName", ReplyAction="*")]
        System.Threading.Tasks.Task<bizapps_test.MVC.AsmxBlogUserServiceReference.GetBlogUserByNameResponse> GetBlogUserByNameAsync(bizapps_test.MVC.AsmxBlogUserServiceReference.GetBlogUserByNameRequest request);
        
        // CODEGEN: Generating message contract since element name incomingUser from namespace http://bloguser.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://bloguser.org/GetBlogUserNameAndPassword", ReplyAction="*")]
        bizapps_test.MVC.AsmxBlogUserServiceReference.GetBlogUserNameAndPasswordResponse GetBlogUserNameAndPassword(bizapps_test.MVC.AsmxBlogUserServiceReference.GetBlogUserNameAndPasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bloguser.org/GetBlogUserNameAndPassword", ReplyAction="*")]
        System.Threading.Tasks.Task<bizapps_test.MVC.AsmxBlogUserServiceReference.GetBlogUserNameAndPasswordResponse> GetBlogUserNameAndPasswordAsync(bizapps_test.MVC.AsmxBlogUserServiceReference.GetBlogUserNameAndPasswordRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace http://bloguser.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://bloguser.org/GetAdminPermission", ReplyAction="*")]
        bizapps_test.MVC.AsmxBlogUserServiceReference.GetAdminPermissionResponse GetAdminPermission(bizapps_test.MVC.AsmxBlogUserServiceReference.GetAdminPermissionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bloguser.org/GetAdminPermission", ReplyAction="*")]
        System.Threading.Tasks.Task<bizapps_test.MVC.AsmxBlogUserServiceReference.GetAdminPermissionResponse> GetAdminPermissionAsync(bizapps_test.MVC.AsmxBlogUserServiceReference.GetAdminPermissionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateBlogUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateBlogUser", Namespace="http://bloguser.org/", Order=0)]
        public bizapps_test.MVC.AsmxBlogUserServiceReference.CreateBlogUserRequestBody Body;
        
        public CreateBlogUserRequest() {
        }
        
        public CreateBlogUserRequest(bizapps_test.MVC.AsmxBlogUserServiceReference.CreateBlogUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://bloguser.org/")]
    public partial class CreateBlogUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public bizapps_test.MVC.AsmxBlogUserServiceReference.BlogUserSoap bloguserSoap;
        
        public CreateBlogUserRequestBody() {
        }
        
        public CreateBlogUserRequestBody(bizapps_test.MVC.AsmxBlogUserServiceReference.BlogUserSoap bloguserSoap) {
            this.bloguserSoap = bloguserSoap;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateBlogUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateBlogUserResponse", Namespace="http://bloguser.org/", Order=0)]
        public bizapps_test.MVC.AsmxBlogUserServiceReference.CreateBlogUserResponseBody Body;
        
        public CreateBlogUserResponse() {
        }
        
        public CreateBlogUserResponse(bizapps_test.MVC.AsmxBlogUserServiceReference.CreateBlogUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://bloguser.org/")]
    public partial class CreateBlogUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int CreateBlogUserResult;
        
        public CreateBlogUserResponseBody() {
        }
        
        public CreateBlogUserResponseBody(int CreateBlogUserResult) {
            this.CreateBlogUserResult = CreateBlogUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateBlogUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateBlogUser", Namespace="http://bloguser.org/", Order=0)]
        public bizapps_test.MVC.AsmxBlogUserServiceReference.UpdateBlogUserRequestBody Body;
        
        public UpdateBlogUserRequest() {
        }
        
        public UpdateBlogUserRequest(bizapps_test.MVC.AsmxBlogUserServiceReference.UpdateBlogUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://bloguser.org/")]
    public partial class UpdateBlogUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public bizapps_test.MVC.AsmxBlogUserServiceReference.BlogUserSoap bloguserSoap;
        
        public UpdateBlogUserRequestBody() {
        }
        
        public UpdateBlogUserRequestBody(bizapps_test.MVC.AsmxBlogUserServiceReference.BlogUserSoap bloguserSoap) {
            this.bloguserSoap = bloguserSoap;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateBlogUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateBlogUserResponse", Namespace="http://bloguser.org/", Order=0)]
        public bizapps_test.MVC.AsmxBlogUserServiceReference.UpdateBlogUserResponseBody Body;
        
        public UpdateBlogUserResponse() {
        }
        
        public UpdateBlogUserResponse(bizapps_test.MVC.AsmxBlogUserServiceReference.UpdateBlogUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://bloguser.org/")]
    public partial class UpdateBlogUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UpdateBlogUserResult;
        
        public UpdateBlogUserResponseBody() {
        }
        
        public UpdateBlogUserResponseBody(int UpdateBlogUserResult) {
            this.UpdateBlogUserResult = UpdateBlogUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteBlogUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteBlogUser", Namespace="http://bloguser.org/", Order=0)]
        public bizapps_test.MVC.AsmxBlogUserServiceReference.DeleteBlogUserRequestBody Body;
        
        public DeleteBlogUserRequest() {
        }
        
        public DeleteBlogUserRequest(bizapps_test.MVC.AsmxBlogUserServiceReference.DeleteBlogUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://bloguser.org/")]
    public partial class DeleteBlogUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public bizapps_test.MVC.AsmxBlogUserServiceReference.BlogUserSoap bloguserSoap;
        
        public DeleteBlogUserRequestBody() {
        }
        
        public DeleteBlogUserRequestBody(bizapps_test.MVC.AsmxBlogUserServiceReference.BlogUserSoap bloguserSoap) {
            this.bloguserSoap = bloguserSoap;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteBlogUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteBlogUserResponse", Namespace="http://bloguser.org/", Order=0)]
        public bizapps_test.MVC.AsmxBlogUserServiceReference.DeleteBlogUserResponseBody Body;
        
        public DeleteBlogUserResponse() {
        }
        
        public DeleteBlogUserResponse(bizapps_test.MVC.AsmxBlogUserServiceReference.DeleteBlogUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://bloguser.org/")]
    public partial class DeleteBlogUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int DeleteBlogUserResult;
        
        public DeleteBlogUserResponseBody() {
        }
        
        public DeleteBlogUserResponseBody(int DeleteBlogUserResult) {
            this.DeleteBlogUserResult = DeleteBlogUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangePasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChangePassword", Namespace="http://bloguser.org/", Order=0)]
        public bizapps_test.MVC.AsmxBlogUserServiceReference.ChangePasswordRequestBody Body;
        
        public ChangePasswordRequest() {
        }
        
        public ChangePasswordRequest(bizapps_test.MVC.AsmxBlogUserServiceReference.ChangePasswordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://bloguser.org/")]
    public partial class ChangePasswordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public bizapps_test.MVC.AsmxBlogUserServiceReference.BlogUserSoap bloguserSoap;
        
        public ChangePasswordRequestBody() {
        }
        
        public ChangePasswordRequestBody(bizapps_test.MVC.AsmxBlogUserServiceReference.BlogUserSoap bloguserSoap) {
            this.bloguserSoap = bloguserSoap;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangePasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChangePasswordResponse", Namespace="http://bloguser.org/", Order=0)]
        public bizapps_test.MVC.AsmxBlogUserServiceReference.ChangePasswordResponseBody Body;
        
        public ChangePasswordResponse() {
        }
        
        public ChangePasswordResponse(bizapps_test.MVC.AsmxBlogUserServiceReference.ChangePasswordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://bloguser.org/")]
    public partial class ChangePasswordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ChangePasswordResult;
        
        public ChangePasswordResponseBody() {
        }
        
        public ChangePasswordResponseBody(int ChangePasswordResult) {
            this.ChangePasswordResult = ChangePasswordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllUsersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllUsers", Namespace="http://bloguser.org/", Order=0)]
        public bizapps_test.MVC.AsmxBlogUserServiceReference.GetAllUsersRequestBody Body;
        
        public GetAllUsersRequest() {
        }
        
        public GetAllUsersRequest(bizapps_test.MVC.AsmxBlogUserServiceReference.GetAllUsersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllUsersRequestBody {
        
        public GetAllUsersRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllUsersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllUsersResponse", Namespace="http://bloguser.org/", Order=0)]
        public bizapps_test.MVC.AsmxBlogUserServiceReference.GetAllUsersResponseBody Body;
        
        public GetAllUsersResponse() {
        }
        
        public GetAllUsersResponse(bizapps_test.MVC.AsmxBlogUserServiceReference.GetAllUsersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://bloguser.org/")]
    public partial class GetAllUsersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public bizapps_test.MVC.AsmxBlogUserServiceReference.BlogUserSoap[] GetAllUsersResult;
        
        public GetAllUsersResponseBody() {
        }
        
        public GetAllUsersResponseBody(bizapps_test.MVC.AsmxBlogUserServiceReference.BlogUserSoap[] GetAllUsersResult) {
            this.GetAllUsersResult = GetAllUsersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBlogUserByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBlogUserById", Namespace="http://bloguser.org/", Order=0)]
        public bizapps_test.MVC.AsmxBlogUserServiceReference.GetBlogUserByIdRequestBody Body;
        
        public GetBlogUserByIdRequest() {
        }
        
        public GetBlogUserByIdRequest(bizapps_test.MVC.AsmxBlogUserServiceReference.GetBlogUserByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://bloguser.org/")]
    public partial class GetBlogUserByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int userId;
        
        public GetBlogUserByIdRequestBody() {
        }
        
        public GetBlogUserByIdRequestBody(int userId) {
            this.userId = userId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBlogUserByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBlogUserByIdResponse", Namespace="http://bloguser.org/", Order=0)]
        public bizapps_test.MVC.AsmxBlogUserServiceReference.GetBlogUserByIdResponseBody Body;
        
        public GetBlogUserByIdResponse() {
        }
        
        public GetBlogUserByIdResponse(bizapps_test.MVC.AsmxBlogUserServiceReference.GetBlogUserByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://bloguser.org/")]
    public partial class GetBlogUserByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public bizapps_test.MVC.AsmxBlogUserServiceReference.BlogUserSoap GetBlogUserByIdResult;
        
        public GetBlogUserByIdResponseBody() {
        }
        
        public GetBlogUserByIdResponseBody(bizapps_test.MVC.AsmxBlogUserServiceReference.BlogUserSoap GetBlogUserByIdResult) {
            this.GetBlogUserByIdResult = GetBlogUserByIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBlogUserByNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBlogUserByName", Namespace="http://bloguser.org/", Order=0)]
        public bizapps_test.MVC.AsmxBlogUserServiceReference.GetBlogUserByNameRequestBody Body;
        
        public GetBlogUserByNameRequest() {
        }
        
        public GetBlogUserByNameRequest(bizapps_test.MVC.AsmxBlogUserServiceReference.GetBlogUserByNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://bloguser.org/")]
    public partial class GetBlogUserByNameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        public GetBlogUserByNameRequestBody() {
        }
        
        public GetBlogUserByNameRequestBody(string userName) {
            this.userName = userName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBlogUserByNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBlogUserByNameResponse", Namespace="http://bloguser.org/", Order=0)]
        public bizapps_test.MVC.AsmxBlogUserServiceReference.GetBlogUserByNameResponseBody Body;
        
        public GetBlogUserByNameResponse() {
        }
        
        public GetBlogUserByNameResponse(bizapps_test.MVC.AsmxBlogUserServiceReference.GetBlogUserByNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://bloguser.org/")]
    public partial class GetBlogUserByNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public bizapps_test.MVC.AsmxBlogUserServiceReference.BlogUserSoap GetBlogUserByNameResult;
        
        public GetBlogUserByNameResponseBody() {
        }
        
        public GetBlogUserByNameResponseBody(bizapps_test.MVC.AsmxBlogUserServiceReference.BlogUserSoap GetBlogUserByNameResult) {
            this.GetBlogUserByNameResult = GetBlogUserByNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBlogUserNameAndPasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBlogUserNameAndPassword", Namespace="http://bloguser.org/", Order=0)]
        public bizapps_test.MVC.AsmxBlogUserServiceReference.GetBlogUserNameAndPasswordRequestBody Body;
        
        public GetBlogUserNameAndPasswordRequest() {
        }
        
        public GetBlogUserNameAndPasswordRequest(bizapps_test.MVC.AsmxBlogUserServiceReference.GetBlogUserNameAndPasswordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://bloguser.org/")]
    public partial class GetBlogUserNameAndPasswordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public bizapps_test.MVC.AsmxBlogUserServiceReference.BlogUserSoap incomingUser;
        
        public GetBlogUserNameAndPasswordRequestBody() {
        }
        
        public GetBlogUserNameAndPasswordRequestBody(bizapps_test.MVC.AsmxBlogUserServiceReference.BlogUserSoap incomingUser) {
            this.incomingUser = incomingUser;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBlogUserNameAndPasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBlogUserNameAndPasswordResponse", Namespace="http://bloguser.org/", Order=0)]
        public bizapps_test.MVC.AsmxBlogUserServiceReference.GetBlogUserNameAndPasswordResponseBody Body;
        
        public GetBlogUserNameAndPasswordResponse() {
        }
        
        public GetBlogUserNameAndPasswordResponse(bizapps_test.MVC.AsmxBlogUserServiceReference.GetBlogUserNameAndPasswordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://bloguser.org/")]
    public partial class GetBlogUserNameAndPasswordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public bizapps_test.MVC.AsmxBlogUserServiceReference.BlogUserSoap GetBlogUserNameAndPasswordResult;
        
        public GetBlogUserNameAndPasswordResponseBody() {
        }
        
        public GetBlogUserNameAndPasswordResponseBody(bizapps_test.MVC.AsmxBlogUserServiceReference.BlogUserSoap GetBlogUserNameAndPasswordResult) {
            this.GetBlogUserNameAndPasswordResult = GetBlogUserNameAndPasswordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAdminPermissionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAdminPermission", Namespace="http://bloguser.org/", Order=0)]
        public bizapps_test.MVC.AsmxBlogUserServiceReference.GetAdminPermissionRequestBody Body;
        
        public GetAdminPermissionRequest() {
        }
        
        public GetAdminPermissionRequest(bizapps_test.MVC.AsmxBlogUserServiceReference.GetAdminPermissionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://bloguser.org/")]
    public partial class GetAdminPermissionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        public GetAdminPermissionRequestBody() {
        }
        
        public GetAdminPermissionRequestBody(string userName) {
            this.userName = userName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAdminPermissionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAdminPermissionResponse", Namespace="http://bloguser.org/", Order=0)]
        public bizapps_test.MVC.AsmxBlogUserServiceReference.GetAdminPermissionResponseBody Body;
        
        public GetAdminPermissionResponse() {
        }
        
        public GetAdminPermissionResponse(bizapps_test.MVC.AsmxBlogUserServiceReference.GetAdminPermissionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://bloguser.org/")]
    public partial class GetAdminPermissionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GetAdminPermissionResult;
        
        public GetAdminPermissionResponseBody() {
        }
        
        public GetAdminPermissionResponseBody(int GetAdminPermissionResult) {
            this.GetAdminPermissionResult = GetAdminPermissionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AsmxBlogUserServiceSoapChannel : bizapps_test.MVC.AsmxBlogUserServiceReference.AsmxBlogUserServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AsmxBlogUserServiceSoapClient : System.ServiceModel.ClientBase<bizapps_test.MVC.AsmxBlogUserServiceReference.AsmxBlogUserServiceSoap>, bizapps_test.MVC.AsmxBlogUserServiceReference.AsmxBlogUserServiceSoap {
        
        public AsmxBlogUserServiceSoapClient() {
        }
        
        public AsmxBlogUserServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AsmxBlogUserServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AsmxBlogUserServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AsmxBlogUserServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bizapps_test.MVC.AsmxBlogUserServiceReference.CreateBlogUserResponse bizapps_test.MVC.AsmxBlogUserServiceReference.AsmxBlogUserServiceSoap.CreateBlogUser(bizapps_test.MVC.AsmxBlogUserServiceReference.CreateBlogUserRequest request) {
            return base.Channel.CreateBlogUser(request);
        }
        
        public int CreateBlogUser(bizapps_test.MVC.AsmxBlogUserServiceReference.BlogUserSoap bloguserSoap) {
            bizapps_test.MVC.AsmxBlogUserServiceReference.CreateBlogUserRequest inValue = new bizapps_test.MVC.AsmxBlogUserServiceReference.CreateBlogUserRequest();
            inValue.Body = new bizapps_test.MVC.AsmxBlogUserServiceReference.CreateBlogUserRequestBody();
            inValue.Body.bloguserSoap = bloguserSoap;
            bizapps_test.MVC.AsmxBlogUserServiceReference.CreateBlogUserResponse retVal = ((bizapps_test.MVC.AsmxBlogUserServiceReference.AsmxBlogUserServiceSoap)(this)).CreateBlogUser(inValue);
            return retVal.Body.CreateBlogUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<bizapps_test.MVC.AsmxBlogUserServiceReference.CreateBlogUserResponse> bizapps_test.MVC.AsmxBlogUserServiceReference.AsmxBlogUserServiceSoap.CreateBlogUserAsync(bizapps_test.MVC.AsmxBlogUserServiceReference.CreateBlogUserRequest request) {
            return base.Channel.CreateBlogUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<bizapps_test.MVC.AsmxBlogUserServiceReference.CreateBlogUserResponse> CreateBlogUserAsync(bizapps_test.MVC.AsmxBlogUserServiceReference.BlogUserSoap bloguserSoap) {
            bizapps_test.MVC.AsmxBlogUserServiceReference.CreateBlogUserRequest inValue = new bizapps_test.MVC.AsmxBlogUserServiceReference.CreateBlogUserRequest();
            inValue.Body = new bizapps_test.MVC.AsmxBlogUserServiceReference.CreateBlogUserRequestBody();
            inValue.Body.bloguserSoap = bloguserSoap;
            return ((bizapps_test.MVC.AsmxBlogUserServiceReference.AsmxBlogUserServiceSoap)(this)).CreateBlogUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bizapps_test.MVC.AsmxBlogUserServiceReference.UpdateBlogUserResponse bizapps_test.MVC.AsmxBlogUserServiceReference.AsmxBlogUserServiceSoap.UpdateBlogUser(bizapps_test.MVC.AsmxBlogUserServiceReference.UpdateBlogUserRequest request) {
            return base.Channel.UpdateBlogUser(request);
        }
        
        public int UpdateBlogUser(bizapps_test.MVC.AsmxBlogUserServiceReference.BlogUserSoap bloguserSoap) {
            bizapps_test.MVC.AsmxBlogUserServiceReference.UpdateBlogUserRequest inValue = new bizapps_test.MVC.AsmxBlogUserServiceReference.UpdateBlogUserRequest();
            inValue.Body = new bizapps_test.MVC.AsmxBlogUserServiceReference.UpdateBlogUserRequestBody();
            inValue.Body.bloguserSoap = bloguserSoap;
            bizapps_test.MVC.AsmxBlogUserServiceReference.UpdateBlogUserResponse retVal = ((bizapps_test.MVC.AsmxBlogUserServiceReference.AsmxBlogUserServiceSoap)(this)).UpdateBlogUser(inValue);
            return retVal.Body.UpdateBlogUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<bizapps_test.MVC.AsmxBlogUserServiceReference.UpdateBlogUserResponse> bizapps_test.MVC.AsmxBlogUserServiceReference.AsmxBlogUserServiceSoap.UpdateBlogUserAsync(bizapps_test.MVC.AsmxBlogUserServiceReference.UpdateBlogUserRequest request) {
            return base.Channel.UpdateBlogUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<bizapps_test.MVC.AsmxBlogUserServiceReference.UpdateBlogUserResponse> UpdateBlogUserAsync(bizapps_test.MVC.AsmxBlogUserServiceReference.BlogUserSoap bloguserSoap) {
            bizapps_test.MVC.AsmxBlogUserServiceReference.UpdateBlogUserRequest inValue = new bizapps_test.MVC.AsmxBlogUserServiceReference.UpdateBlogUserRequest();
            inValue.Body = new bizapps_test.MVC.AsmxBlogUserServiceReference.UpdateBlogUserRequestBody();
            inValue.Body.bloguserSoap = bloguserSoap;
            return ((bizapps_test.MVC.AsmxBlogUserServiceReference.AsmxBlogUserServiceSoap)(this)).UpdateBlogUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bizapps_test.MVC.AsmxBlogUserServiceReference.DeleteBlogUserResponse bizapps_test.MVC.AsmxBlogUserServiceReference.AsmxBlogUserServiceSoap.DeleteBlogUser(bizapps_test.MVC.AsmxBlogUserServiceReference.DeleteBlogUserRequest request) {
            return base.Channel.DeleteBlogUser(request);
        }
        
        public int DeleteBlogUser(bizapps_test.MVC.AsmxBlogUserServiceReference.BlogUserSoap bloguserSoap) {
            bizapps_test.MVC.AsmxBlogUserServiceReference.DeleteBlogUserRequest inValue = new bizapps_test.MVC.AsmxBlogUserServiceReference.DeleteBlogUserRequest();
            inValue.Body = new bizapps_test.MVC.AsmxBlogUserServiceReference.DeleteBlogUserRequestBody();
            inValue.Body.bloguserSoap = bloguserSoap;
            bizapps_test.MVC.AsmxBlogUserServiceReference.DeleteBlogUserResponse retVal = ((bizapps_test.MVC.AsmxBlogUserServiceReference.AsmxBlogUserServiceSoap)(this)).DeleteBlogUser(inValue);
            return retVal.Body.DeleteBlogUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<bizapps_test.MVC.AsmxBlogUserServiceReference.DeleteBlogUserResponse> bizapps_test.MVC.AsmxBlogUserServiceReference.AsmxBlogUserServiceSoap.DeleteBlogUserAsync(bizapps_test.MVC.AsmxBlogUserServiceReference.DeleteBlogUserRequest request) {
            return base.Channel.DeleteBlogUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<bizapps_test.MVC.AsmxBlogUserServiceReference.DeleteBlogUserResponse> DeleteBlogUserAsync(bizapps_test.MVC.AsmxBlogUserServiceReference.BlogUserSoap bloguserSoap) {
            bizapps_test.MVC.AsmxBlogUserServiceReference.DeleteBlogUserRequest inValue = new bizapps_test.MVC.AsmxBlogUserServiceReference.DeleteBlogUserRequest();
            inValue.Body = new bizapps_test.MVC.AsmxBlogUserServiceReference.DeleteBlogUserRequestBody();
            inValue.Body.bloguserSoap = bloguserSoap;
            return ((bizapps_test.MVC.AsmxBlogUserServiceReference.AsmxBlogUserServiceSoap)(this)).DeleteBlogUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bizapps_test.MVC.AsmxBlogUserServiceReference.ChangePasswordResponse bizapps_test.MVC.AsmxBlogUserServiceReference.AsmxBlogUserServiceSoap.ChangePassword(bizapps_test.MVC.AsmxBlogUserServiceReference.ChangePasswordRequest request) {
            return base.Channel.ChangePassword(request);
        }
        
        public int ChangePassword(bizapps_test.MVC.AsmxBlogUserServiceReference.BlogUserSoap bloguserSoap) {
            bizapps_test.MVC.AsmxBlogUserServiceReference.ChangePasswordRequest inValue = new bizapps_test.MVC.AsmxBlogUserServiceReference.ChangePasswordRequest();
            inValue.Body = new bizapps_test.MVC.AsmxBlogUserServiceReference.ChangePasswordRequestBody();
            inValue.Body.bloguserSoap = bloguserSoap;
            bizapps_test.MVC.AsmxBlogUserServiceReference.ChangePasswordResponse retVal = ((bizapps_test.MVC.AsmxBlogUserServiceReference.AsmxBlogUserServiceSoap)(this)).ChangePassword(inValue);
            return retVal.Body.ChangePasswordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<bizapps_test.MVC.AsmxBlogUserServiceReference.ChangePasswordResponse> bizapps_test.MVC.AsmxBlogUserServiceReference.AsmxBlogUserServiceSoap.ChangePasswordAsync(bizapps_test.MVC.AsmxBlogUserServiceReference.ChangePasswordRequest request) {
            return base.Channel.ChangePasswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<bizapps_test.MVC.AsmxBlogUserServiceReference.ChangePasswordResponse> ChangePasswordAsync(bizapps_test.MVC.AsmxBlogUserServiceReference.BlogUserSoap bloguserSoap) {
            bizapps_test.MVC.AsmxBlogUserServiceReference.ChangePasswordRequest inValue = new bizapps_test.MVC.AsmxBlogUserServiceReference.ChangePasswordRequest();
            inValue.Body = new bizapps_test.MVC.AsmxBlogUserServiceReference.ChangePasswordRequestBody();
            inValue.Body.bloguserSoap = bloguserSoap;
            return ((bizapps_test.MVC.AsmxBlogUserServiceReference.AsmxBlogUserServiceSoap)(this)).ChangePasswordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bizapps_test.MVC.AsmxBlogUserServiceReference.GetAllUsersResponse bizapps_test.MVC.AsmxBlogUserServiceReference.AsmxBlogUserServiceSoap.GetAllUsers(bizapps_test.MVC.AsmxBlogUserServiceReference.GetAllUsersRequest request) {
            return base.Channel.GetAllUsers(request);
        }
        
        public bizapps_test.MVC.AsmxBlogUserServiceReference.BlogUserSoap[] GetAllUsers() {
            bizapps_test.MVC.AsmxBlogUserServiceReference.GetAllUsersRequest inValue = new bizapps_test.MVC.AsmxBlogUserServiceReference.GetAllUsersRequest();
            inValue.Body = new bizapps_test.MVC.AsmxBlogUserServiceReference.GetAllUsersRequestBody();
            bizapps_test.MVC.AsmxBlogUserServiceReference.GetAllUsersResponse retVal = ((bizapps_test.MVC.AsmxBlogUserServiceReference.AsmxBlogUserServiceSoap)(this)).GetAllUsers(inValue);
            return retVal.Body.GetAllUsersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<bizapps_test.MVC.AsmxBlogUserServiceReference.GetAllUsersResponse> bizapps_test.MVC.AsmxBlogUserServiceReference.AsmxBlogUserServiceSoap.GetAllUsersAsync(bizapps_test.MVC.AsmxBlogUserServiceReference.GetAllUsersRequest request) {
            return base.Channel.GetAllUsersAsync(request);
        }
        
        public System.Threading.Tasks.Task<bizapps_test.MVC.AsmxBlogUserServiceReference.GetAllUsersResponse> GetAllUsersAsync() {
            bizapps_test.MVC.AsmxBlogUserServiceReference.GetAllUsersRequest inValue = new bizapps_test.MVC.AsmxBlogUserServiceReference.GetAllUsersRequest();
            inValue.Body = new bizapps_test.MVC.AsmxBlogUserServiceReference.GetAllUsersRequestBody();
            return ((bizapps_test.MVC.AsmxBlogUserServiceReference.AsmxBlogUserServiceSoap)(this)).GetAllUsersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bizapps_test.MVC.AsmxBlogUserServiceReference.GetBlogUserByIdResponse bizapps_test.MVC.AsmxBlogUserServiceReference.AsmxBlogUserServiceSoap.GetBlogUserById(bizapps_test.MVC.AsmxBlogUserServiceReference.GetBlogUserByIdRequest request) {
            return base.Channel.GetBlogUserById(request);
        }
        
        public bizapps_test.MVC.AsmxBlogUserServiceReference.BlogUserSoap GetBlogUserById(int userId) {
            bizapps_test.MVC.AsmxBlogUserServiceReference.GetBlogUserByIdRequest inValue = new bizapps_test.MVC.AsmxBlogUserServiceReference.GetBlogUserByIdRequest();
            inValue.Body = new bizapps_test.MVC.AsmxBlogUserServiceReference.GetBlogUserByIdRequestBody();
            inValue.Body.userId = userId;
            bizapps_test.MVC.AsmxBlogUserServiceReference.GetBlogUserByIdResponse retVal = ((bizapps_test.MVC.AsmxBlogUserServiceReference.AsmxBlogUserServiceSoap)(this)).GetBlogUserById(inValue);
            return retVal.Body.GetBlogUserByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<bizapps_test.MVC.AsmxBlogUserServiceReference.GetBlogUserByIdResponse> bizapps_test.MVC.AsmxBlogUserServiceReference.AsmxBlogUserServiceSoap.GetBlogUserByIdAsync(bizapps_test.MVC.AsmxBlogUserServiceReference.GetBlogUserByIdRequest request) {
            return base.Channel.GetBlogUserByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<bizapps_test.MVC.AsmxBlogUserServiceReference.GetBlogUserByIdResponse> GetBlogUserByIdAsync(int userId) {
            bizapps_test.MVC.AsmxBlogUserServiceReference.GetBlogUserByIdRequest inValue = new bizapps_test.MVC.AsmxBlogUserServiceReference.GetBlogUserByIdRequest();
            inValue.Body = new bizapps_test.MVC.AsmxBlogUserServiceReference.GetBlogUserByIdRequestBody();
            inValue.Body.userId = userId;
            return ((bizapps_test.MVC.AsmxBlogUserServiceReference.AsmxBlogUserServiceSoap)(this)).GetBlogUserByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bizapps_test.MVC.AsmxBlogUserServiceReference.GetBlogUserByNameResponse bizapps_test.MVC.AsmxBlogUserServiceReference.AsmxBlogUserServiceSoap.GetBlogUserByName(bizapps_test.MVC.AsmxBlogUserServiceReference.GetBlogUserByNameRequest request) {
            return base.Channel.GetBlogUserByName(request);
        }
        
        public bizapps_test.MVC.AsmxBlogUserServiceReference.BlogUserSoap GetBlogUserByName(string userName) {
            bizapps_test.MVC.AsmxBlogUserServiceReference.GetBlogUserByNameRequest inValue = new bizapps_test.MVC.AsmxBlogUserServiceReference.GetBlogUserByNameRequest();
            inValue.Body = new bizapps_test.MVC.AsmxBlogUserServiceReference.GetBlogUserByNameRequestBody();
            inValue.Body.userName = userName;
            bizapps_test.MVC.AsmxBlogUserServiceReference.GetBlogUserByNameResponse retVal = ((bizapps_test.MVC.AsmxBlogUserServiceReference.AsmxBlogUserServiceSoap)(this)).GetBlogUserByName(inValue);
            return retVal.Body.GetBlogUserByNameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<bizapps_test.MVC.AsmxBlogUserServiceReference.GetBlogUserByNameResponse> bizapps_test.MVC.AsmxBlogUserServiceReference.AsmxBlogUserServiceSoap.GetBlogUserByNameAsync(bizapps_test.MVC.AsmxBlogUserServiceReference.GetBlogUserByNameRequest request) {
            return base.Channel.GetBlogUserByNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<bizapps_test.MVC.AsmxBlogUserServiceReference.GetBlogUserByNameResponse> GetBlogUserByNameAsync(string userName) {
            bizapps_test.MVC.AsmxBlogUserServiceReference.GetBlogUserByNameRequest inValue = new bizapps_test.MVC.AsmxBlogUserServiceReference.GetBlogUserByNameRequest();
            inValue.Body = new bizapps_test.MVC.AsmxBlogUserServiceReference.GetBlogUserByNameRequestBody();
            inValue.Body.userName = userName;
            return ((bizapps_test.MVC.AsmxBlogUserServiceReference.AsmxBlogUserServiceSoap)(this)).GetBlogUserByNameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bizapps_test.MVC.AsmxBlogUserServiceReference.GetBlogUserNameAndPasswordResponse bizapps_test.MVC.AsmxBlogUserServiceReference.AsmxBlogUserServiceSoap.GetBlogUserNameAndPassword(bizapps_test.MVC.AsmxBlogUserServiceReference.GetBlogUserNameAndPasswordRequest request) {
            return base.Channel.GetBlogUserNameAndPassword(request);
        }
        
        public bizapps_test.MVC.AsmxBlogUserServiceReference.BlogUserSoap GetBlogUserNameAndPassword(bizapps_test.MVC.AsmxBlogUserServiceReference.BlogUserSoap incomingUser) {
            bizapps_test.MVC.AsmxBlogUserServiceReference.GetBlogUserNameAndPasswordRequest inValue = new bizapps_test.MVC.AsmxBlogUserServiceReference.GetBlogUserNameAndPasswordRequest();
            inValue.Body = new bizapps_test.MVC.AsmxBlogUserServiceReference.GetBlogUserNameAndPasswordRequestBody();
            inValue.Body.incomingUser = incomingUser;
            bizapps_test.MVC.AsmxBlogUserServiceReference.GetBlogUserNameAndPasswordResponse retVal = ((bizapps_test.MVC.AsmxBlogUserServiceReference.AsmxBlogUserServiceSoap)(this)).GetBlogUserNameAndPassword(inValue);
            return retVal.Body.GetBlogUserNameAndPasswordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<bizapps_test.MVC.AsmxBlogUserServiceReference.GetBlogUserNameAndPasswordResponse> bizapps_test.MVC.AsmxBlogUserServiceReference.AsmxBlogUserServiceSoap.GetBlogUserNameAndPasswordAsync(bizapps_test.MVC.AsmxBlogUserServiceReference.GetBlogUserNameAndPasswordRequest request) {
            return base.Channel.GetBlogUserNameAndPasswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<bizapps_test.MVC.AsmxBlogUserServiceReference.GetBlogUserNameAndPasswordResponse> GetBlogUserNameAndPasswordAsync(bizapps_test.MVC.AsmxBlogUserServiceReference.BlogUserSoap incomingUser) {
            bizapps_test.MVC.AsmxBlogUserServiceReference.GetBlogUserNameAndPasswordRequest inValue = new bizapps_test.MVC.AsmxBlogUserServiceReference.GetBlogUserNameAndPasswordRequest();
            inValue.Body = new bizapps_test.MVC.AsmxBlogUserServiceReference.GetBlogUserNameAndPasswordRequestBody();
            inValue.Body.incomingUser = incomingUser;
            return ((bizapps_test.MVC.AsmxBlogUserServiceReference.AsmxBlogUserServiceSoap)(this)).GetBlogUserNameAndPasswordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bizapps_test.MVC.AsmxBlogUserServiceReference.GetAdminPermissionResponse bizapps_test.MVC.AsmxBlogUserServiceReference.AsmxBlogUserServiceSoap.GetAdminPermission(bizapps_test.MVC.AsmxBlogUserServiceReference.GetAdminPermissionRequest request) {
            return base.Channel.GetAdminPermission(request);
        }
        
        public int GetAdminPermission(string userName) {
            bizapps_test.MVC.AsmxBlogUserServiceReference.GetAdminPermissionRequest inValue = new bizapps_test.MVC.AsmxBlogUserServiceReference.GetAdminPermissionRequest();
            inValue.Body = new bizapps_test.MVC.AsmxBlogUserServiceReference.GetAdminPermissionRequestBody();
            inValue.Body.userName = userName;
            bizapps_test.MVC.AsmxBlogUserServiceReference.GetAdminPermissionResponse retVal = ((bizapps_test.MVC.AsmxBlogUserServiceReference.AsmxBlogUserServiceSoap)(this)).GetAdminPermission(inValue);
            return retVal.Body.GetAdminPermissionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<bizapps_test.MVC.AsmxBlogUserServiceReference.GetAdminPermissionResponse> bizapps_test.MVC.AsmxBlogUserServiceReference.AsmxBlogUserServiceSoap.GetAdminPermissionAsync(bizapps_test.MVC.AsmxBlogUserServiceReference.GetAdminPermissionRequest request) {
            return base.Channel.GetAdminPermissionAsync(request);
        }
        
        public System.Threading.Tasks.Task<bizapps_test.MVC.AsmxBlogUserServiceReference.GetAdminPermissionResponse> GetAdminPermissionAsync(string userName) {
            bizapps_test.MVC.AsmxBlogUserServiceReference.GetAdminPermissionRequest inValue = new bizapps_test.MVC.AsmxBlogUserServiceReference.GetAdminPermissionRequest();
            inValue.Body = new bizapps_test.MVC.AsmxBlogUserServiceReference.GetAdminPermissionRequestBody();
            inValue.Body.userName = userName;
            return ((bizapps_test.MVC.AsmxBlogUserServiceReference.AsmxBlogUserServiceSoap)(this)).GetAdminPermissionAsync(inValue);
        }
    }
}
